SET TERM ^;
CREATE OR ALTER PACKAGE IMPORT_PROD_TIPO_PA
AS
BEGIN
  PROCEDURE GARANTIR_ID_DESCR
  (
    NOME NOME_REDU_DOM NOT NULL, 
    PROD_TIPO_ID ID_SHORT_DOM
  )
  RETURNS
  (
    IMPORT_PROD_TIPO_ID ID_DOM
  );
  
  PROCEDURE APAGAR_DO;
END^

----- body -----

RECREATE PACKAGE BODY IMPORT_PROD_TIPO_PA
AS
BEGIN
  PROCEDURE GARANTIR_ID_DESCR
  (
    NOME NOME_REDU_DOM NOT NULL,
    PROD_TIPO_ID ID_SHORT_DOM
  )
  RETURNS 
  (
    IMPORT_PROD_TIPO_ID ID_DOM
  )
  AS
  BEGIN
    SELECT IMPORT_PROD_TIPO_ID FROM IMPORT_PROD_TIPO WHERE NOME = :NOME INTO :IMPORT_PROD_TIPO_ID;
    
    IF (IMPORT_PROD_TIPO_ID IS NOT NULL) THEN
    BEGIN
      UPDATE IMPORT_PROD_TIPO SET PROD_TIPO_ID = :PROD_TIPO_ID WHERE IMPORT_PROD_TIPO_ID = :IMPORT_PROD_TIPO_ID;
    END
    ELSE
    BEGIN
      IMPORT_PROD_TIPO_ID = NEXT VALUE FOR IMPORT_PROD_TIPO_SEQ;
      INSERT INTO IMPORT_PROD_TIPO (IMPORT_PROD_TIPO_ID, NOME, PROD_TIPO_ID) VALUES (:IMPORT_PROD_TIPO_ID, :NOME, :PROD_TIPO_ID);
    END
    SUSPEND;
  END
  
  PROCEDURE APAGAR_DO
  AS
  BEGIN
    EXECUTE STATEMENT('ALTER SEQUENCE IMPORT_PROD_TIPO_SEQ RESTART WITH 1;');
    DELETE FROM IMPORT_PROD_TIPO;
  END
END^
SET TERM ;^
