SET TERM ^;
CREATE OR ALTER PACKAGE LOJA_INICIAL_PA
AS
BEGIN
  PROCEDURE INS
  (
    LOJA_ID ID_SHORT_DOM NOT NULL
    , APELIDO NOME_REDU_DOM NOT NULL
    , SELECIONADO SELECIONADO_DOM NOT NULL
    , PESSOA_ID ID_DOM NOT NULL
    , MACHINE_ID ID_SHORT_DOM
);  

  PROCEDURE SELECIONADO_GET
  RETURNS
  (
    LOJA_ID SMALLINT
    , APELIDO NOME_REDU_DOM
  );

  PROCEDURE LISTA_GET
  (
    APELIDO_BUSCA NOME_REDU_DOM
  )
  RETURNS
  (
    LOJA_ID SMALLINT
    , APELIDO NOME_REDU_DOM
    , SELECIONADO BOOLEAN
  );

  PROCEDURE LOJA_SET
  (
    LOJA_ID ID_SHORT_DOM NOT NULL
    , APELIDO NOME_REDU_DOM NOT NULL
    , SELECIONADO SELECIONADO_DOM NOT NULL
  );
  PROCEDURE BYID_GET
  (
    LOJA_ID ID_SHORT_DOM NOT NULL
  )
  RETURNS
  (
    APELIDO NOME_REDU_DOM
    , SELECIONADO BOOLEAN
  );

  PROCEDURE GARANTIR
  (
    LOJA_ID ID_SHORT_DOM NOT NULL
    , APELIDO NOME_REDU_DOM NOT NULL
    , SELECIONADO SELECIONADO_DOM NOT NULL
    , PESSOA_ID ID_DOM NOT NULL
    , MACHINE_ID ID_SHORT_DOM
  );
END^
/*
----------
BODY
----------
*/
RECREATE PACKAGE BODY LOJA_INICIAL_PA
AS
BEGIN
  PROCEDURE INS
  (
    LOJA_ID ID_SHORT_DOM NOT NULL
    , APELIDO NOME_REDU_DOM NOT NULL
    , SELECIONADO SELECIONADO_DOM NOT NULL
    , PESSOA_ID ID_DOM NOT NULL
    , MACHINE_ID ID_SHORT_DOM
  )
  AS
  BEGIN
    INSERT INTO LOJA(
      LOJA_ID
      , APELIDO
      , SELECIONADO
    )VALUES(
      :LOJA_ID
      , :APELIDO
      , :SELECIONADO
    );

    IF (:SELECIONADO) THEN
      EXECUTE PROCEDURE AMBIENTE_SIS_PA.LOJA_ID_SET(:LOJA_ID);
  END
  
  PROCEDURE SELECIONADO_GET
  RETURNS
  (
    LOJA_ID SMALLINT
    , APELIDO NOME_REDU_DOM
  )
  AS
  BEGIN
    FOR SELECT L.LOJA_ID, L.APELIDO FROM LOJA L WHERE L.SELECIONADO = TRUE 
    INTO :LOJA_ID, :APELIDO 
    DO 
    SUSPEND;
  END
  PROCEDURE LISTA_GET
  (
    APELIDO_BUSCA NOME_REDU_DOM
  )
  RETURNS
  (
    LOJA_ID SMALLINT
    , APELIDO NOME_REDU_DOM
    , SELECIONADO BOOLEAN
  )
  AS 
  BEGIN 
    IF (TRIM(APELIDO_BUSCA) = '') THEN 
      FOR SELECT L.LOJA_ID, L.APELIDO, L.SELECIONADO FROM LOJA L INTO :LOJA_ID, :APELIDO, :SELECIONADO DO SUSPEND; 
    ELSE 
      FOR SELECT L.LOJA_ID, L.APELIDO, L.SELECIONADO FROM LOJA L WHERE L.APELIDO LIKE '%'||:APELIDO_BUSCA||'%' INTO :LOJA_ID, :APELIDO, :SELECIONADO DO SUSPEND; 
  END
  
  PROCEDURE LOJA_SET 
  (
    LOJA_ID ID_SHORT_DOM NOT NULL
    , APELIDO NOME_REDU_DOM NOT NULL
    , SELECIONADO SELECIONADO_DOM NOT NULL
  )
   AS 
   BEGIN 
     UPDATE LOJA SET APELIDO = :APELIDO, SELECIONADO = :SELECIONADO WHERE LOJA_ID = :LOJA_ID; 
    IF (:SELECIONADO) THEN
      EXECUTE PROCEDURE AMBIENTE_SIS_PA.LOJA_ID_SET(:LOJA_ID);
   END

   PROCEDURE BYID_GET
  (
    LOJA_ID ID_SHORT_DOM NOT NULL
  )
  RETURNS
  (
    APELIDO NOME_REDU_DOM
    , SELECIONADO BOOLEAN
  )
  AS  
  BEGIN  
    SELECT FIRST(1) L.APELIDO, L.SELECIONADO FROM LOJA L WHERE L.LOJA_ID = :LOJA_ID INTO :APELIDO, :SELECIONADO;  
    SUSPEND;
  END
  
  PROCEDURE GARANTIR
  (
    LOJA_ID ID_SHORT_DOM NOT NULL
    , APELIDO NOME_REDU_DOM NOT NULL
    , SELECIONADO SELECIONADO_DOM NOT NULL
    , PESSOA_ID ID_DOM NOT NULL
    , MACHINE_ID ID_SHORT_DOM
  )
  AS
  BEGIN
    UPDATE OR INSERT INTO LOJA (LOJA_ID, APELIDO, SELECIONADO)
    VALUES (:LOJA_ID, :APELIDO, :SELECIONADO)
    MATCHING (LOJA_ID);
    
    IF (:SELECIONADO) THEN
      EXECUTE PROCEDURE AMBIENTE_SIS_PA.LOJA_ID_SET(:LOJA_ID);
  END

END^
SET TERM ;^
