SET TERM ^;
CREATE OR ALTER PACKAGE LOJA_MANUT_PA
AS
BEGIN
  PROCEDURE LISTA_GET
  RETURNS
  (
    LO.ATIVO,
    LO.LOJA_ID,
    LO.APELIDO, 
    PE.PESSOA_ID, 
    PE.NOME, 
    PE.NOME_FANTASIA, 
    PE.GENERO_ID, 
    PE.ESTADO_CIVIL_ID, 
    PE.C, 
    PE.I, 
    PE.M, 
    PE.M_UF, 
    PE.EMAIL, 
    PE.DT_NASC, 
    PE.EDITADO_EM, 
    PE.CRIADO_EM


    NUM Integer
    , DTH_INS DTH_INS_DOM
    , ASSUNTO VARCHAR(200)
    , OBJETIVO OBS1_DOM
    , OBS VARCHAR(1000)
  );
END^

RECREATE PACKAGE BODY LOJA_MANUT_PA
AS
BEGIN
END^
SET TERM ;^
