SET TERM ^;
CREATE OR ALTER PACKAGE ATIVIDADE_ECONOMICA_SIS_PA
AS
BEGIN
  PROCEDURE SELECIONE
  (
    ATIVIDADE_ECONOMICA_SIS_ID ID_CHAR_DOM NOT NULL
  );

  PROCEDURE ID_SELECIONADO
  RETURNS
  (
    ATIVIDADE_ECONOMICA_SIS_ID CHAR(1)
  );
END^

RECREATE PACKAGE BODY ATIVIDADE_ECONOMICA_SIS_PA
AS
BEGIN
  PROCEDURE SELECIONE
  (
    ATIVIDADE_ECONOMICA_SIS_ID ID_CHAR_DOM NOT NULL
  )
  AS
  BEGIN
    UPDATE ATIVIDADE_ECONOMICA_SIS SET SELECIONADO = (ATIVIDADE_ECONOMICA_SIS_ID = :ATIVIDADE_ECONOMICA_SIS_ID);
  END

  PROCEDURE ID_SELECIONADO
  RETURNS
  (
    ATIVIDADE_ECONOMICA_SIS_ID CHAR(1)
  )
  AS
  BEGIN
    FOR 
      SELECT ATIVIDADE_ECONOMICA_SIS_ID
      FROM ATIVIDADE_ECONOMICA_SIS
      WHERE SELECIONADO
      INTO :ATIVIDADE_ECONOMICA_SIS_ID
    DO
      SUSPEND;
  END
END^

SET TERM ;^
