SET TERM ^;
CREATE OR ALTER PACKAGE SEQUENCES_ATUAIS_PA
AS
BEGIN
  -- SEQUENCES_ATUAIS.VALUES_GET DEF
  PROCEDURE VALUES_GET
  RETURNS
  (
    CAIXA_SESSAO_SEQ BIGINT,
    EST_MOV_SEQ BIGINT,
    LOG_SEQ BIGINT,
    PESSOA_SEQ BIGINT,
    VENDA_SEQ BIGINT
  );
END^
/*
----------
BODY
----------
*/
RECREATE PACKAGE BODY SEQUENCES_ATUAIS_PA
AS
BEGIN
  -- SEQUENCES_ATUAIS.VALUES_GET IMP
  PROCEDURE VALUES_GET
  RETURNS
  (
    CAIXA_SESSAO_SEQ BIGINT,
    EST_MOV_SEQ BIGINT,
    LOG_SEQ BIGINT,
    PESSOA_SEQ BIGINT,
    VENDA_SEQ BIGINT
  )
  AS
  BEGIN
    -- SEQUENCES_ATUAIS.VALUES_GET COD
    SELECT GEN_ID(CAIXA_SESSAO_SEQ, 0) FROM RDB$DATABASE INTO :CAIXA_SESSAO_SEQ;
    SELECT GEN_ID(EST_MOV_SEQ, 0) FROM RDB$DATABASE INTO :EST_MOV_SEQ;
    SELECT GEN_ID(LOG_SEQ, 0) FROM RDB$DATABASE INTO :LOG_SEQ;
    SELECT GEN_ID(PESSOA_SEQ, 0) FROM RDB$DATABASE INTO :PESSOA_SEQ;
    SELECT GEN_ID(VENDA_SEQ, 0) FROM RDB$DATABASE INTO :VENDA_SEQ;
    
    SUSPEND;
  END
END^
SET TERM ;^

/*
in "C:\Pr\app\bantu\bantu-sis\Src\Externos\DBUpdates Complementos\Complementos\Sis\SEQUENCES_ATUAIS_PA_TERM.sql";
*/

/*
SELECT CAIXA_SESSAO_SEQ, EST_MOV_SEQ, LOG_SEQ, PESSOA_SEQ, VENDA_SEQ FROM SEQUENCES_ATUAIS_PA.VALUES_GET;
*/