/*
in "C:\Pr\app\bantu\bantu-sis\Src\Externos\DBUpdates Complementos\Complementos\Estoque\EST_SALDO_RETAG_PA.sql";

SELECT * FROM EST_SALDO_RETAG_PA.EST_MOV_DTH_MIN_GET;
*/

SET TERM ^;
CREATE OR ALTER PACKAGE EST_SALDO_RETAG_PA
AS
BEGIN
  PROCEDURE EST_MOV_DTH_MIN_GET
  RETURNS
  (
    DTH_MIN_RET TIMESTAMP
  );

  PROCEDURE EST_SALDO_GAR
  (
    DTH TIMESTAMP NOT NULL,
    LOJA_ID ID_SHORT_DOM NOT NULL,
    PROD_ID ID_DOM NOT NULL,
    QTD QTD_DOM NOT NULL
  );

END^

----- body -----

RECREATE PACKAGE BODY EST_SALDO_RETAG_PA
AS
BEGIN
  PROCEDURE EST_MOV_DTH_MIN_GET
  RETURNS
  (
    DTH_MIN_RET TIMESTAMP
  )
  AS
  BEGIN
    SELECT MIN(CRIADO_EM)
    FROM EST_MOV
    INTO :DTH_MIN_RET;
    SUSPEND;
  END

  PROCEDURE EST_SALDO_GAR
  (
    DTH TIMESTAMP NOT NULL,
    LOJA_ID ID_SHORT_DOM NOT NULL,
    PROD_ID ID_DOM NOT NULL,
    QTD QTD_DOM NOT NULL
  )
  AS
  BEGIN
    UPDATE OR INSERT INTO EST_SALDO (LOJA_ID, PROD_ID, DTH, QTD)
    VALUES (:LOJA_ID, :PROD_ID, :DTH, :QTD)
    MATCHING (LOJA_ID, PROD_ID);

    UPDATE OR INSERT INTO EST_SALDO_HIST (DTH, LOJA_ID, PROD_ID, QTD)
    VALUES (:DTH, :LOJA_ID, :PROD_ID, :QTD)
    MATCHING (DTH, LOJA_ID, PROD_ID);
  END

END^
SET TERM ;^
