SET TERM ^;
CREATE OR ALTER PACKAGE RETAG_PROD_BUSCA_PA
AS
BEGIN
  PROCEDURE BY_BARRAS_GET
  (
    COD_BARRAS CHAR(14) NOT NULL
  )
  RETURNS 
  (
    PROD_ID ID_DOM,
    DESCR_RED PROD_DESCR_RED_DOM,
    FABR_NOME NOME_REDU_DOM,
    BALANCA_EXIGE BOOLEAN,
    CUSTO CUSTO_DOM,
    MARGEM MARGEM_DOM,
    PRECO PRECO_DOM,
    BARRAS VARCHAR(233)
  );

  PROCEDURE BY_ID_GET
  (
    PROD_ID_BUSCA ID_DOM NOT NULL
  )
  RETURNS 
  (
    PROD_ID ID_DOM,
    DESCR_RED PROD_DESCR_RED_DOM,
    FABR_NOME NOME_REDU_DOM,
    BALANCA_EXIGE BOOLEAN,
    CUSTO CUSTO_DOM,
    MARGEM MARGEM_DOM,
    PRECO PRECO_DOM,
    BARRAS VARCHAR(233)
  );

  PROCEDURE BY_DESCR_RED_GET
  (
    STR_BUSCA PROD_DESCR_RED_DOM NOT NULL
  )
  RETURNS 
  (
    PROD_ID ID_DOM,
    DESCR_RED PROD_DESCR_RED_DOM,
    FABR_NOME NOME_REDU_DOM,
    BALANCA_EXIGE BOOLEAN,
    CUSTO CUSTO_DOM,
    MARGEM MARGEM_DOM,
    PRECO PRECO_DOM,
    BARRAS VARCHAR(233)
  );

END^
    
----- body -----

RECREATE PACKAGE BODY RETAG_PROD_BUSCA_PA
AS
BEGIN 
  PROCEDURE BY_BARRAS_GET
  (
    COD_BARRAS CHAR(14) NOT NULL
  )
  RETURNS 
  (
    PROD_ID ID_DOM,
    DESCR_RED PROD_DESCR_RED_DOM,
    FABR_NOME NOME_REDU_DOM,
    BALANCA_EXIGE BOOLEAN,
    CUSTO CUSTO_DOM,
    MARGEM MARGEM_DOM,
    PRECO PRECO_DOM,
    BARRAS VARCHAR(233)
  )
AS
BEGIN
  FOR
    SELECT
      P.PROD_ID,
      P.DESCR_RED,
      F.NOME AS FABR,
      C.BALANCA_EXIGE,
      PC.CUSTO,
      C.MARGEM,
      PR.PRECO,
      LIST(B.COD_BARRAS) BARRAS

    FROM AMBIENTE_SIS A

    JOIN PROD_COMPL C ON
    A.LOJA_ID = C.LOJA_ID
    
    JOIN PROD P ON
    P.PROD_ID = C.PROD_ID
    
    JOIN FABR F ON
    F.FABR_ID = P.FABR_ID

    LEFT JOIN PROD_BARRAS B ON
    P.PROD_ID = B.PROD_ID
    
    LEFT JOIN PROD_PRECO PR ON
    P.PROD_ID = PR.PROD_ID
    AND A.LOJA_ID = PR.LOJA_ID
    AND A.TERMINAL_ID = PR.TERMINAL_ID

    LEFT JOIN PROD_CUSTO PC ON
    P.PROD_ID = PC.PROD_ID
    AND A.LOJA_ID = PC.LOJA_ID
    AND A.TERMINAL_ID = PC.TERMINAL_ID
    
    WHERE B.COD_BARRAS = :COD_BARRAS

    GROUP BY 
      P.PROD_ID,
      P.DESCR_RED,
      F.NOME,
      C.BALANCA_EXIGE,
      PC.CUSTO,
      C.MARGEM,
      PR.PRECO
    INTO
      :PROD_ID,
      :DESCR_RED, 
      :FABR_NOME,
      :BALANCA_EXIGE,
      :CUSTO,
      :MARGEM,
      :PRECO,
      :BARRAS
    DO
      SUSPEND;
  END

  PROCEDURE BY_ID_GET
  (
    PROD_ID_BUSCA ID_DOM NOT NULL
  ) RETURNS 
  (
    PROD_ID ID_DOM,
    DESCR_RED PROD_DESCR_RED_DOM,
    FABR_NOME NOME_REDU_DOM,
    BALANCA_EXIGE BOOLEAN,
    CUSTO CUSTO_DOM,
    MARGEM MARGEM_DOM,
    PRECO PRECO_DOM,
    BARRAS VARCHAR(233)
  )
  AS
  BEGIN
    FOR
      SELECT
        P.PROD_ID,
        P.DESCR_RED,
        F.NOME AS FABR,
        C.BALANCA_EXIGE,
        PC.CUSTO,
        C.MARGEM,
        PR.PRECO,
        LIST(B.COD_BARRAS) BARRAS

      FROM AMBIENTE_SIS A

      JOIN PROD_COMPL C ON
      A.LOJA_ID = C.LOJA_ID
      
      JOIN PROD P ON
      P.PROD_ID = C.PROD_ID
      
      JOIN FABR F ON
      F.FABR_ID = P.FABR_ID

      LEFT JOIN PROD_BARRAS B ON
      P.PROD_ID = B.PROD_ID
      
      LEFT JOIN PROD_PRECO PR ON
      P.PROD_ID = PR.PROD_ID
      AND A.LOJA_ID = PR.LOJA_ID
      AND A.TERMINAL_ID = PR.TERMINAL_ID

      LEFT JOIN PROD_CUSTO PC ON
      P.PROD_ID = PC.PROD_ID
      AND A.LOJA_ID = PC.LOJA_ID
      AND A.TERMINAL_ID = PC.TERMINAL_ID

      WHERE P.PROD_ID = :PROD_ID_BUSCA

      GROUP BY 
        P.PROD_ID,
        P.DESCR_RED,
        F.NOME,
        C.BALANCA_EXIGE,
        PC.CUSTO,
        C.MARGEM,
        PR.PRECO
      INTO
        :PROD_ID,
        :DESCR_RED, 
        :FABR_NOME,
        :BALANCA_EXIGE,
        :CUSTO,
        :MARGEM,
        :PRECO,
        :BARRAS
      DO
        SUSPEND;
  END

  PROCEDURE BY_DESCR_RED_GET
  (
    STR_BUSCA PROD_DESCR_RED_DOM NOT NULL
  )
  RETURNS 
  (
    PROD_ID ID_DOM,
    DESCR_RED PROD_DESCR_RED_DOM,
    FABR_NOME NOME_REDU_DOM,
    BALANCA_EXIGE BOOLEAN,
    CUSTO CUSTO_DOM,
    MARGEM MARGEM_DOM,
    PRECO PRECO_DOM,
    BARRAS VARCHAR(233)
  )
  AS
    DECLARE QTD_REGS_ENCONTRADOS INTEGER;
  BEGIN
    SELECT COUNT(*)
    FROM PROD P
    WHERE P.DESCR_RED LIKE '%' || :STR_BUSCA || '%'
    INTO :QTD_REGS_ENCONTRADOS;

    IF (:QTD_REGS_ENCONTRADOS <> 1) THEN
    BEGIN
      :PROD_ID = NULL;
      :DESCR_RED = NULL;
      :FABR_NOME = NULL;
      :BALANCA_EXIGE = NULL;
      :CUSTO = NULL;
      :MARGEM = NULL;
      :PRECO = NULL;
      :BARRAS = NULL;
      SUSPEND;
      EXIT; 
    END

    SELECT FIRST(1)
      P.PROD_ID,
      P.DESCR_RED,
      F.NOME AS FABR,
      C.BALANCA_EXIGE,
      PC.CUSTO,
      C.MARGEM,
      PR.PRECO,
      LIST(B.COD_BARRAS) BARRAS

    FROM AMBIENTE_SIS A

    JOIN PROD_COMPL C ON
    A.LOJA_ID = C.LOJA_ID
    
    JOIN PROD P ON
    P.PROD_ID = C.PROD_ID
    
    JOIN FABR F ON
    F.FABR_ID = P.FABR_ID

    LEFT JOIN PROD_BARRAS B ON
    P.PROD_ID = B.PROD_ID
    
    LEFT JOIN PROD_PRECO PR ON
    P.PROD_ID = PR.PROD_ID
    AND A.LOJA_ID = PR.LOJA_ID
    AND A.TERMINAL_ID = PR.TERMINAL_ID

    LEFT JOIN PROD_CUSTO PC ON
    P.PROD_ID = PC.PROD_ID
    AND A.LOJA_ID = PC.LOJA_ID
    AND A.TERMINAL_ID = PC.TERMINAL_ID

    WHERE P.DESCR_RED LIKE '%' || :STR_BUSCA || '%'

    GROUP BY 
      P.PROD_ID,
      P.DESCR_RED,
      F.NOME,
      C.BALANCA_EXIGE,
      PC.CUSTO,
      C.MARGEM,
      PR.PRECO
    INTO
      :PROD_ID,
      :DESCR_RED, 
      :FABR_NOME,
      :BALANCA_EXIGE,
      :CUSTO,
      :MARGEM,
      :PRECO,
      :BARRAS;

    SUSPEND;
  END
END^
SET TERM ;^

/*
SELECT * FROM RETAG_PROD_BUSCA_PA.BY_BARRAS_GET('8617627500060');
SQL> SELECT FIRST(10) * FROM PROD_BARRAS;

     PROD_ID   ORDEM COD_BARRAS
============ ======= ==============
           2       1 8617627500060
           3       1 7869549490313
           4       1 7862052001816
           5       1 4260113520673
           6       1 7869549465311
           7       1 7869549465304
           8       1 7869549435079
           9       1 7822080068250
          10       1 6532846321574
          11       1 6901755718674

SELECT * FROM RETAG_PROD_BUSCA_PA.BY_ID_GET(2);



SQL> SELECT FIRST(10) PROD_ID, DESCR_RED FROM PROD;

     PROD_ID DESCR_RED
============ =============================
           2 CANETA P CELULA FASHIO MOBILE
           3 CANETA PARA CELULAR
           4 OTG CONECTION S-K07
           5 OTG GALAX TAB CONNE KIT S-K03
           6 ADAPTADOR DE CHIP NOOSY
           7 ADAPTADOR DE CHIP NANO SIM
           8 CARREGADOR UNIVERSAL FEITUN
           9 SUPORTE DE TELEFONE CARMOUNT
          10 SUP D TELEFONE PHONE H MASTON
          11 ADAPTADOR WI-FI 900MBPS

SELECT * FROM RETAG_PROD_BUSCA_PA.BY_DESCR_RED_GET('B');
SELECT * FROM RETAG_PROD_BUSCA_PA.BY_DESCR_RED_GET('ADAPTADOR WI-FI 900MBPS');
*/


/*
in "C:\Pr\app\bantu\bantu-sis\Src\Externos\DBUpdates Complementos\Complementos\Estoque\RETAG_PROD_BUSCA_PA.sql";
*/
