desejo abrir o isql do Firebird através do cmd do windows.
ele está localizado neste caminho:
"C:\Program Files\Firebird\Firebird_4_0\isql.exe"
e eu quero que ele conecte neste banco de dados:
"C:\Pr\app\bantu\bantu-sis\retag\DADOS.FDB"

como ficaria a linha decomando?

"C:\Program Files\Firebird\Firebird_4_0\isql.exe" -u SYSDBA -p MASTERKEY "C:\Pr\app\bantu\bantu-sis\retag\DADOS.FDB" 

DROP TABLE PROD_CATEG;

CREATE TABlE PROD_CATEG
(
PROD_CATEG_ID INTEGER NOT NULL
, NOME VARCHAR(32)
);

ALTER TABLE PROD_CATEG
ADD CONSTRAINT PROD_CATEG_PK
PRIMARY KEY (PROD_CATEG_ID);

CREATE GENERATOR PROD_CATEG_G;
--SET GENERATOR PROD_CATEG_G TO 3;
--SELECT NEXT VALUE FOR PROD_CATEG_G FROM RDB$DATABASE;

INSERT INTO PROD_CATEG(PROD_CATEG_ID,NOME) VALUES (1, 'LIMPEZA');
INSERT INTO PROD_CATEG(PROD_CATEG_ID,NOME) VALUES (2, 'MATINAIS');
INSERT INTO PROD_CATEG(PROD_CATEG_ID,NOME) VALUES (3, 'GRAOS');
COMMIT;



DROP TABLE USU;

CREATE TABlE USU
(
USU_ID INTEGER NOT NULL
, NOME_USU VARCHAR(32)
, NOME_EXIB VARCHAR(32)
, SENHA VARCHAR(32)
);

ALTER TABLE USU
ADD CONSTRAINT USU_PK
PRIMARY KEY (USU_ID);

CREATE GENERATOR USU_G;
--SET GENERATOR PROD_CATEG_G TO 3;
--SELECT NEXT VALUE FOR PROD_CATEG_G FROM RDB$DATABASE;

INSERT INTO PROD_CATEG(PROD_CATEG_ID,NOME) VALUES (1, 'LIMPEZA');
INSERT INTO PROD_CATEG(PROD_CATEG_ID,NOME) VALUES (2, 'MATINAIS');
INSERT INTO PROD_CATEG(PROD_CATEG_ID,NOME) VALUES (3, 'GRAOS');
COMMIT;


