/*
in "C:\Pr\app\bantu\bantu-sis\Src\Externos\DBUpdates Complementos\Complementos\Assist\SYNC_DO_TERMINAL_SIS_PA.sql";
*/

SET TERM ^;
CREATE OR ALTER PACKAGE SYNC_DO_TERMINAL_SIS_PA
AS
BEGIN
  PROCEDURE ULTIMO_GET(TERMINAL_ID SMALLINT NOT NULL)
  RETURNS (LOG_ID_ULTIMO_TRAZIDO_RET BIGINT);
  
  PROCEDURE ATUALIZE(TERMINAL_ID SMALLINT NOT NULL, LOG_ID_ULTIMO_TRAZIDO BIGINT NOT NULL);
END^
/*
----------
BODY
----------
*/
RECREATE PACKAGE BODY SYNC_DO_TERMINAL_SIS_PA
AS
BEGIN
  PROCEDURE ULTIMO_GET(TERMINAL_ID SMALLINT NOT NULL)
    RETURNS (LOG_ID_ULTIMO_TRAZIDO_RET BIGINT)
  AS
  BEGIN
    SELECT LOG_ID_ULTIMO_TRAZIDO
    FROM SYNC_DO_TERMINAL_SIS
    WHERE TERMINAL_ID = :TERMINAL_ID
    INTO :LOG_ID_ULTIMO_TRAZIDO_RET;
    
    IF (LOG_ID_ULTIMO_TRAZIDO_RET IS NULL) THEN
    BEGIN
      INSERT INTO SYNC_DO_TERMINAL_SIS (TERMINAL_ID, LOG_ID_ULTIMO_TRAZIDO)
      VALUES (:TERMINAL_ID, 0);
      LOG_ID_ULTIMO_TRAZIDO_RET = 0;
    END
    SUSPEND;
  END

  PROCEDURE ATUALIZE(TERMINAL_ID SMALLINT NOT NULL, LOG_ID_ULTIMO_TRAZIDO BIGINT NOT NULL)
  AS
  BEGIN
    UPDATE SYNC_DO_TERMINAL_SIS
    SET LOG_ID_ULTIMO_TRAZIDO = :LOG_ID_ULTIMO_TRAZIDO
    WHERE TERMINAL_ID = :TERMINAL_ID;
  END
END^
SET TERM ;^
