/*
in "C:\Pr\app\bantu\bantu-sis\Src\Externos\DBUpdates Complementos\Complementos\Assist\TERM_LOG_HIST_PA.sql";
*/

SET TERM ^;
CREATE OR ALTER PACKAGE TERM_LOG_HIST_PA
AS
BEGIN
  PROCEDURE ULTIMO_LOG_ID_GET
  RETURNS (LOG_ID_RET BIGINT);

  PROCEDURE TEVE_CAIXA_SESSAO
  (
    LOG_ID_INI BIGINT
    , LOG_ID_FIN BIGINT
  )
  RETURNS
  (
    LOJA_ID ID_SHORT_DOM,
    TERMINAL_ID ID_SHORT_DOM,
    LOG_ID BIGINT,
    DTH TIMESTAMP,
    PESSOA_TERMINAL_ID ID_SHORT_DOM,
    PESSOA_ID ID_DOM,
    MODULO_SIS_ID ID_CHAR_DOM,
    ACAO_SIS_ID ID_CHAR_DOM,
    FEATURE_SIS_ID ID_SHORT_DOM,
    MACHINE_ID ID_SHORT_DOM,
    ORDEM SMALLINT,
    LOJA_ID_ENVOLVIDO ID_SHORT_DOM,
    TERMINAL_ID_ENVOLVIDO ID_SHORT_DOM,
    ID_ENVOLVIDO BIGINT,
    ORDEM_ENVOLVIDO SMALLINT,
    ID_ENVOLVIDO2 BIGINT,
    SESS_ID ID_DOM,
    SESS_LOG_ID BIGINT,
    ABERTO BOOLEAN,
    CONFERIDO BOOLEAN
  );
END^

------ BODY

RECREATE PACKAGE BODY TERM_LOG_HIST_PA
AS
BEGIN
  PROCEDURE ULTIMO_LOG_ID_GET
  RETURNS (LOG_ID_RET BIGINT)
  AS
  BEGIN
    SELECT
      MAX(LOG_ID)
    FROM LOG
    INTO :LOG_ID_RET;
    
    IF (:LOG_ID_RET IS NULL) THEN
      :LOG_ID_RET = 0;
      
    SUSPEND;
  END

  PROCEDURE TEVE_CAIXA_SESSAO
  (
    LOG_ID_INI BIGINT
    , LOG_ID_FIN BIGINT
  )
  RETURNS
  (
    LOJA_ID ID_SHORT_DOM,
    TERMINAL_ID ID_SHORT_DOM,
    LOG_ID BIGINT,
    DTH TIMESTAMP,
    PESSOA_TERMINAL_ID ID_SHORT_DOM,
    PESSOA_ID ID_DOM,
    MODULO_SIS_ID ID_CHAR_DOM,
    ACAO_SIS_ID ID_CHAR_DOM,
    FEATURE_SIS_ID ID_SHORT_DOM,
    MACHINE_ID ID_SHORT_DOM,
    ORDEM SMALLINT,
    LOJA_ID_ENVOLVIDO ID_SHORT_DOM,
    TERMINAL_ID_ENVOLVIDO ID_SHORT_DOM,
    ID_ENVOLVIDO BIGINT,
    ORDEM_ENVOLVIDO SMALLINT,
    ID_ENVOLVIDO2 BIGINT,
    SESS_ID ID_DOM,
    SESS_LOG_ID BIGINT,
    ABERTO BOOLEAN,
    CONFERIDO BOOLEAN
  )
  AS
  BEGIN
    FOR
      WITH L AS (
      SELECT LOJA_ID, TERMINAL_ID, LOG_ID, DTH,
        PESSOA_TERMINAL_ID, PESSOA_ID, MODULO_SIS_ID,
        ACAO_SIS_ID, FEATURE_SIS_ID, MACHINE_ID 
      FROM LOG
      WHERE LOG_ID >= :LOG_ID_INI AND LOG_ID <= :LOG_ID_FIN
    ), LE AS (  
      SELECT LOJA_ID, TERMINAL_ID, LOG_ID, ORDEM,
      LOJA_ID_ENVOLVIDO, TERMINAL_ID_ENVOLVIDO,
      ID_ENVOLVIDO, ORDEM_ENVOLVIDO, ID_ENVOLVIDO2
      FROM LOG_ENVOLVE_ID
      WHERE LOG_ID >= :LOG_ID_INI AND LOG_ID <= :LOG_ID_FIN
    ), SES AS (
      SELECT LOJA_ID, TERMINAL_ID, SESS_ID,
        SESS_LOG_ID, ABERTO, CONFERIDO
      FROM CAIXA_SESSAO
    )
    SELECT 
        L.LOJA_ID,
        L.TERMINAL_ID,
        L.LOG_ID,
        L.DTH,
        L.PESSOA_TERMINAL_ID,
        L.PESSOA_ID,
        L.MODULO_SIS_ID,
        L.ACAO_SIS_ID,
        L.FEATURE_SIS_ID,
        L.MACHINE_ID,
        LE.ORDEM,
        LE.LOJA_ID_ENVOLVIDO,
        LE.TERMINAL_ID_ENVOLVIDO,
        LE.ID_ENVOLVIDO,
        LE.ORDEM_ENVOLVIDO,
        LE.ID_ENVOLVIDO2,
        SES.SESS_ID,
        L.LOG_ID AS SESS_LOG_ID,
        SES.ABERTO,
        SES.CONFERIDO
    FROM L
    JOIN SES ON
      L.LOJA_ID = SES.LOJA_ID
      AND L.TERMINAL_ID = SES.TERMINAL_ID
      AND L.LOG_ID = SES.SESS_LOG_ID
    JOIN LE ON
      L.LOJA_ID = LE.LOJA_ID
      AND L.TERMINAL_ID = LE.TERMINAL_ID
      AND L.LOG_ID = LE.LOG_ID
    INTO
      :LOJA_ID,
      :TERMINAL_ID,
      :LOG_ID,
      :DTH,
      :PESSOA_TERMINAL_ID,
      :PESSOA_ID,
      :MODULO_SIS_ID,
      :ACAO_SIS_ID,
      :FEATURE_SIS_ID,
      :MACHINE_ID,
      :ORDEM,
      :LOJA_ID_ENVOLVIDO,
      :TERMINAL_ID_ENVOLVIDO,
      :ID_ENVOLVIDO,
      :ORDEM_ENVOLVIDO,
      :ID_ENVOLVIDO2,
      :SESS_ID,
      :SESS_LOG_ID,
      :ABERTO,
      :CONFERIDO
    DO
      SUSPEND;
  END
END^
SET TERM ;^
