program Starter;

uses
  Vcl.Forms,
  btu.sta.ui.PrincForm in 'ui\btu.sta.ui.PrincForm.pas' {PrincForm},
  btu.sta.exec_u in 'sta\btu.sta.exec_u.pas',
  btu.sta.ui.ConfigForm in 'ui\btu.sta.ui.ConfigForm.pas' {StarterFormConfig},
  ControlsReposition in '..\bantu-lib\sis\ui\FormDecorators\ControlsAlign\ControlsReposition.pas',
  btu.sta.MaqNomeEdFrame in 'ui\btu.sta.MaqNomeEdFrame.pas' {MaqNomeEdFrame: TFrame},
  btu.lib.ui.Img.DataModule in '..\bantu-lib\sis\ui\FormDecorators\btu.lib.ui.Img.DataModule.pas' {SisImgDataModule: TDataModule},
  btu.lib.config.machineid in '..\bantu-lib\sis\config\btu.lib.config.machineid.pas',
  btu.lib.config in '..\bantu-lib\sis\config\btu.lib.config.pas',
  btu.lib.config.machineid_u in '..\bantu-lib\sis\config\btu.lib.config.machineid_u.pas',
  btu.lib.config_u in '..\bantu-lib\sis\config\btu.lib.config_u.pas',
  btu.lib.config.factory in '..\bantu-lib\sis\config\btu.lib.config.factory.pas',
  winversion in '..\bantu-lib\sis\win\winversion.pas',
  winplatform in '..\bantu-lib\sis\win\winplatform.pas',
  btu.lib.files in '..\bantu-lib\sis\files\btu.lib.files.pas',
  btu.lib.win.VersionInfo in '..\bantu-lib\sis\win\btu.lib.win.VersionInfo.pas',
  btu.lib.win.VersionInfo_u in '..\bantu-lib\sis\win\btu.lib.win.VersionInfo_u.pas',
  btu.lib.win.factory in '..\bantu-lib\sis\win\btu.lib.win.factory.pas',
  btu.lib.sis.constants in '..\bantu-lib\sis\sis\btu.lib.sis.constants.pas',
  btu.lib.types.constants in '..\bantu-lib\sis\types\btu.lib.types.constants.pas',
  btu.lib.win.constants in '..\bantu-lib\sis\win\btu.lib.win.constants.pas',
  btu.sta.constants in 'sta\btu.sta.constants.pas',
  btu.sis.di.ui.constants in '..\bantu-lib\sis\di\ui\btu.sis.di.ui.constants.pas',
  btn.lib.types.strings in '..\bantu-lib\sis\types\str\btn.lib.types.strings.pas',
  btu.lib.usu.Usuario in '..\bantu-lib\sis\usu\btu.lib.usu.Usuario.pas',
  btu.lib.usu.Usuario_u in '..\bantu-lib\sis\usu\btu.lib.usu.Usuario_u.pas',
  btu.lib.usu.factory in '..\bantu-lib\sis\usu\btu.lib.usu.factory.pas',
  btu.lib.debug in '..\bantu-lib\sis\debug\btu.lib.debug.pas',
  btn.lib.ui.controls.utils in '..\bantu-lib\sis\ui\controls\btn.lib.ui.controls.utils.pas',
  btu.lib.lists.HashItem_i in '..\bantu-lib\sis\lists\btu.lib.lists.HashItem_i.pas',
  btu.lib.lists.HashItem_u in '..\bantu-lib\sis\lists\btu.lib.lists.HashItem_u.pas',
  btu.lib.lists.HashItemList_i in '..\bantu-lib\sis\lists\btu.lib.lists.HashItemList_i.pas',
  btu.lib.lists.HashItemList_u in '..\bantu-lib\sis\lists\btu.lib.lists.HashItemList_u.pas',
  btu.lib.lists.IdItem in '..\bantu-lib\sis\lists\btu.lib.lists.IdItem.pas',
  btu.lib.lists.IdItemList_i in '..\bantu-lib\sis\lists\btu.lib.lists.IdItemList_i.pas',
  btu.lib.lists.IdItemList_u in '..\bantu-lib\sis\lists\btu.lib.lists.IdItemList_u.pas',
  btu.lib.lists.factory in '..\bantu-lib\sis\lists\btu.lib.lists.factory.pas',
  btu.lib.lists.IdItem_u in '..\bantu-lib\sis\lists\btu.lib.lists.IdItem_u.pas',
  btu.lib.entit.loja in '..\bantu-lib\sis\entit\btu.lib.entit.loja.pas',
  btu.lib.entit.loja_u in '..\bantu-lib\sis\entit\btu.lib.entit.loja_u.pas',
  btu.lib.entit.factory in '..\bantu-lib\sis\entit\btu.lib.entit.factory.pas',
  btu.sis.ui.io.output in '..\bantu-lib\sis\ui\io\output\btu.sis.ui.io.output.pas',
  btu.sis.ui.io.log in '..\bantu-lib\sis\ui\io\log\btu.sis.ui.io.log.pas',
  btu.sis.ui.io.log_u in '..\bantu-lib\sis\ui\io\log\btu.sis.ui.io.log_u.pas',
  btu.sis.ui.io.output.mudo_u in '..\bantu-lib\sis\ui\io\output\btu.sis.ui.io.output.mudo_u.pas',
  btu.sis.ui.io.log.LogFile_u in '..\bantu-lib\sis\ui\io\log\btu.sis.ui.io.log.LogFile_u.pas',
  btu.sis.ui.io.log.LogRecord in '..\bantu-lib\sis\ui\io\log\btu.sis.ui.io.log.LogRecord.pas',
  btu.sis.ui.io.log.LogRecord_u in '..\bantu-lib\sis\ui\io\log\btu.sis.ui.io.log.LogRecord_u.pas',
  btu.sis.ui.io.log.factory in '..\bantu-lib\sis\ui\io\log\btu.sis.ui.io.log.factory.pas',
  btu.lib.types.bool.utils in '..\bantu-lib\sis\types\bool\btu.lib.types.bool.utils.pas',
  btu.lib.win.pastas in '..\bantu-lib\sis\win\btu.lib.win.pastas.pas',
  btu.lib.db.firebird.utils in '..\bantu-lib\sis\db\firebird\btu.lib.db.firebird.utils.pas',
  btu.lib.db.firebird.types in '..\bantu-lib\sis\db\firebird\btu.lib.db.firebird.types.pas',
  btu.sta.exec_xml_u in 'sta\btu.sta.exec_xml_u.pas',
  btu.lib.db.types in '..\bantu-lib\sis\db\btu.lib.db.types.pas',
  btu.lib.db.factory in '..\bantu-lib\sis\db\btu.lib.db.factory.pas',
  btu.lib.db.dbms.info_u in '..\bantu-lib\sis\db\dbms\btu.lib.db.dbms.info_u.pas',
  btu.lib.win.registry in '..\bantu-lib\sis\win\registry\btu.lib.win.registry.pas',
  btu.sta.exec.testes_u in 'sta\btu.sta.exec.testes_u.pas',
  btu.sta.exec.testes.reg_u in 'sta\btu.sta.exec.testes.reg_u.pas',
  FDacDM_u in '..\bantu-lib\sis\db\fdac_acces\FDacDM_u.pas' {FDacDM: TDataModule},
  btu.lib.win.execute in '..\bantu-lib\sis\win\btu.lib.win.execute.pas',
  btu.lib.win.execute_u in '..\bantu-lib\sis\win\btu.lib.win.execute_u.pas',
  btu.lib.sis.execute in '..\bantu-lib\sis\sis\btu.lib.sis.execute.pas',
  btu.lib.sis.execute_u in '..\bantu-lib\sis\sis\btu.lib.sis.execute_u.pas',
  btu.sis.ui.io.output.form_u in '..\bantu-lib\sis\ui\io\output\output.form\btu.sis.ui.io.output.form_u.pas' {OutputForm},
  btu.sis.ui.io.output.toform_u in '..\bantu-lib\sis\ui\io\output\output.form\btu.sis.ui.io.output.toform_u.pas',
  btu.sis.ui.io.factory in '..\bantu-lib\sis\ui\io\btu.sis.ui.io.factory.pas',
  btu.lib.db.updater in '..\bantu-lib\sis\db\updater\btu.lib.db.updater.pas',
  btu.lib.db.updater_u in '..\bantu-lib\sis\db\updater\btu.lib.db.updater_u.pas',
  btu.lib.db.updater.factory in '..\bantu-lib\sis\db\updater\btu.lib.db.updater.factory.pas',
  btu.lib.db.updater.firebird_u in '..\bantu-lib\sis\db\updater\btu.lib.db.updater.firebird_u.pas',
  btu.lib.db.firebird.info in '..\bantu-lib\sis\db\firebird\btu.lib.db.firebird.info.pas',
  btu.lib.db.dbms in '..\bantu-lib\sis\db\dbms\btu.lib.db.dbms.pas',
  btu.lib.db.dbms.firebird_u in '..\bantu-lib\sis\db\dbms\btu.lib.db.dbms.firebird_u.pas',
  btn.lib.types.integers in '..\bantu-lib\sis\types\int\btn.lib.types.integers.pas',
  btu.lib.db.connection.firedac_u in '..\bantu-lib\sis\db\dbconnect\btu.lib.db.connection.firedac_u.pas',
  btu.lib.db.connection_u in '..\bantu-lib\sis\db\dbconnect\btu.lib.db.connection_u.pas',
  btn.lib.types.str.TStrings_u in '..\bantu-lib\sis\types\str\btn.lib.types.str.TStrings_u.pas',
  btu.lib.db.query_u in '..\bantu-lib\sis\db\dbconnect\btu.lib.db.query_u.pas',
  btu.lib.db.sqloperation_u in '..\bantu-lib\sis\db\dbconnect\btu.lib.db.sqloperation_u.pas',
  btu.lib.db.query.firedac_u in '..\bantu-lib\sis\db\dbconnect\btu.lib.db.query.firedac_u.pas',
  btu.sis.db.updater.utils in '..\bantu-lib\sis\db\updater\btu.sis.db.updater.utils.pas',
  btu.lib.db.updater.firebird.GetSql_u in '..\bantu-lib\sis\db\updater\btu.lib.db.updater.firebird.GetSql_u.pas',
  btu.lib.db.updater.campo in '..\bantu-lib\sis\db\updater\btu.lib.db.updater.campo.pas',
  btu.lib.db.updater.comando.fb.createtable_u in '..\bantu-lib\sis\db\updater\btu.lib.db.updater.comando.fb.createtable_u.pas',
  btu.lib.db.updater.campo_u in '..\bantu-lib\sis\db\updater\btu.lib.db.updater.campo_u.pas',
  btu.lib.db.updater.comando in '..\bantu-lib\sis\db\updater\btu.lib.db.updater.comando.pas',
  btu.lib.db.updater.constants_u in '..\bantu-lib\sis\db\updater\btu.lib.db.updater.constants_u.pas',
  btu.lib.db.updater.campo.list in '..\bantu-lib\sis\db\updater\btu.lib.db.updater.campo.list.pas',
  btu.lib.db.updater.campo.list_u in '..\bantu-lib\sis\db\updater\btu.lib.db.updater.campo.list_u.pas',
  btu.lib.db.updater.comando.fb.createoralterprocedure_u in '..\bantu-lib\sis\db\updater\btu.lib.db.updater.comando.fb.createoralterprocedure_u.pas',
  btu.lib.db.updater.comando.list in '..\bantu-lib\sis\db\updater\btu.lib.db.updater.comando.list.pas',
  btu.lib.db.updater.comando.list_u in '..\bantu-lib\sis\db\updater\btu.lib.db.updater.comando.list_u.pas',
  btu.lib.db.updater.comando.fb_u in '..\bantu-lib\sis\db\updater\btu.lib.db.updater.comando.fb_u.pas',
  btu.sis.ui.io.output.exibirpausa.form_u in '..\bantu-lib\sis\ui\io\output\output.form\btu.sis.ui.io.output.exibirpausa.form_u.pas' {ExibirPausaF},
  btu.lib.db.exec_u in '..\bantu-lib\sis\db\dbconnect\btu.lib.db.exec_u.pas',
  btu.lib.db.exec.firedac_u in '..\bantu-lib\sis\db\dbconnect\btu.lib.db.exec.firedac_u.pas',
  btu.sta.exec.testes.strings_u in 'sta\btu.sta.exec.testes.strings_u.pas',
  btu.lib.db.updater.operations in '..\bantu-lib\sis\db\updater\btu.lib.db.updater.operations.pas',
  btu.lib.db.updater.operations.fb_u in '..\bantu-lib\sis\db\updater\btu.lib.db.updater.operations.fb_u.pas',
  btu.lib.db.updater.comando.fb.createoralterpackage_u in '..\bantu-lib\sis\db\updater\btu.lib.db.updater.comando.fb.createoralterpackage_u.pas',
  btu.lib.db.firebird.GetSql in '..\bantu-lib\sis\db\firebird\btu.lib.db.firebird.GetSql.pas',
  btu.lib.db.updater.comando.fb.createdomains_u in '..\bantu-lib\sis\db\updater\btu.lib.db.updater.comando.fb.createdomains_u.pas',
  btu.lib.sis.clipb_u in '..\bantu-lib\sis\sis\btu.lib.sis.clipb_u.pas',
  btu.lib.db.dbms.config in '..\bantu-lib\sis\db\dbms\btu.lib.db.dbms.config.pas',
  btu.lib.db.dbms.config_u in '..\bantu-lib\sis\db\dbms\btu.lib.db.dbms.config_u.pas',
  btu.lib.db.dbms.config.firebird_u in '..\bantu-lib\sis\db\dbms\btu.lib.db.dbms.config.firebird_u.pas',
  btu.sta.exec.testes.csv_u in 'sta\btu.sta.exec.testes.csv_u.pas',
  btu.lib.db.updater.comando.fb.ensurerecords_u in '..\bantu-lib\sis\db\updater\btu.lib.db.updater.comando.fb.ensurerecords_u.pas',
  btu.lib.lists.TextoItem in '..\bantu-lib\sis\lists\TextList\btu.lib.lists.TextoItem.pas',
  btu.lib.lists.TextoItem_u in '..\bantu-lib\sis\lists\TextList\btu.lib.lists.TextoItem_u.pas',
  btu.lib.lists.TextoList in '..\bantu-lib\sis\lists\TextList\btu.lib.lists.TextoList.pas',
  btu.lib.lists.TextoList_u in '..\bantu-lib\sis\lists\TextList\btu.lib.lists.TextoList_u.pas',
  btu.lib.db.updater.comando.fb.createsequence_u in '..\bantu-lib\sis\db\updater\btu.lib.db.updater.comando.fb.createsequence_u.pas',
  btu.lib.db.updater.comando.fb.createforeignkey_u in '..\bantu-lib\sis\db\updater\btu.lib.db.updater.comando.fb.createforeignkey_u.pas',
  btu.lib.lists.LojaTermIdItem in '..\bantu-lib\sis\lists\btu.lib.lists.LojaTermIdItem.pas',
  btu.lib.lists.LojaTermIdItem_u in '..\bantu-lib\sis\lists\btu.lib.lists.LojaTermIdItem_u.pas',
  btu.lib.entit.LojaTermId.utils in '..\bantu-lib\sis\entit\usuario\btu.lib.entit.LojaTermId.utils.pas',
  btn.lib.types.strings.crypt in '..\bantu-lib\sis\types\str\btn.lib.types.strings.crypt.pas',
  btu.sta.exec.testes.crypt_u in 'sta\btu.sta.exec.testes.crypt_u.pas',
  btu.lib.win.execs in '..\bantu-lib\sis\win\btu.lib.win.execs.pas';

{$R *.res}

begin
  Application.Initialize;
//  Application.MainFormOnTaskbar := True;
  Application.MainFormOnTaskbar := False;
  Application.ShowMainForm := False;
  Application.CreateForm(TPrincForm, PrincForm);
  Application.CreateForm(TFDacDM, FDacDM);
  Application.CreateForm(TExibirPausaF, ExibirPausaF);
  Application.Run;
end.
