SET TERM ^;
CREATE OR ALTER PACKAGE ENDERECO_PA
AS
BEGIN
  PROCEDURE UF_SIGLA_LISTA_GET
  RETURNS (
      UF_SIGLA CHAR(2),
--      UF_NOME NOME_REDU_DOM,
      UF_IBGE_ID ID_SHORT_DOM
  );
  
/*  PROCEDURE MUNICIPIO_LISTA_GET
  RETURNS
  (
      
  );*/
END^

----- body -----
--SELECT * FROM ENDERECO_PA.MUNICIPIO_LISTA_GET;

RECREATE PACKAGE BODY ENDERECO_PA
AS
BEGIN
  PROCEDURE UF_SIGLA_LISTA_GET
  RETURNS (
      UF_SIGLA CHAR(2),
--      UF_NOME NOME_REDU_DOM,
      UF_IBGE_ID ID_SHORT_DOM
  )
  AS
  BEGIN
      FOR SELECT
          UF_SIGLA,
--          UF_NOME,
          UF_IBGE_ID
      FROM UF
      ORDER BY UF_SIGLA
      INTO :UF_SIGLA,
--          :UF_NOME,
          :UF_IBGE_ID
      DO
      BEGIN
          SUSPEND;
      END
  END
  
  /*PROCEDURE MUNICIPIO_LISTA_GET
  RETURNS
  (
      
  )
  AS
  BEGIN
    SELECT RECORD_COUNT FROM PROD_PA.PROD_RECORD_COUNT_GET INTO :PROD_RECORD_COUNT_RET;
    SUSPEND;
  END*/
END^
SET TERM ;^
