SET TERM ^;
CREATE OR ALTER PACKAGE FUNCIONARIO_USUARIO_MANUT_PA
AS
BEGIN 
  PROCEDURE LISTA_GET 
  RETURNS 
  (
    LOJA_ID ID_SHORT_DOM,
    TERMINAL_ID ID_SHORT_DOM,
    PESSOA_ID ID_DOM,
    
    NOME VARCHAR(60),
    APELIDO VARCHAR(20),
    
    GENERO_ID CHAR(1),
    GENERO_DESCR NOME_CURTO_DOM,
    
    ESTADO_CIVIL_ID CHAR(1),
    ESTADO_CIVIL_DESCR NOME_CURTO_DOM,
    
    C VARCHAR(15),
    I VARCHAR(15),
    M VARCHAR(15),
    M_UF CHAR(2),
    
    EMAIL VARCHAR(50),
    DT_NASC DATE,
    ATIVO BOOLEAN,
    
    PESS_CRIADO_EM TIMESTAMP,
    PESS_ALTERADO_EM TIMESTAMP,
    
    LOGRADOURO VARCHAR(70),
    NUMERO NOME_DOM,
    COMPLEMENTO NOME_DOM,
    BAIRRO NOME_DOM,
    
    UF_SIGLA CHAR(2),
    CEP CHAR(8),
    
    MUNICIPIO_IBGE_ID CHAR(5),
    MUNICIPIO_NOME NOME_DOM,
    
    DDD CHAR(2),
    FONE1 NOME_CURTO_DOM,
    FONE2 NOME_CURTO_DOM,
    FONE3 NOME_CURTO_DOM,
    
    CONTATO NOME_DOM,
    REFERENCIA OBS1_DOM,
    
    ENDER_CRIADO_EM TIMESTAMP,
    ENDER_ALTERADO_EM TIMESTAMP,
    
    NOME_DE_USUARIO NOME_REDU_DOM,
    SENHA SENHA_DOM,
    CRY_VER ID_SHORT_DOM
  );
END^ 
----- BODY -----

RECREATE PACKAGE BODY FUNCIONARIO_USUARIO_MANUT_PA
AS 
BEGIN
  PROCEDURE LISTA_GET 
  RETURNS 
  (
    LOJA_ID ID_SHORT_DOM,
    TERMINAL_ID ID_SHORT_DOM,
    PESSOA_ID ID_DOM,
    
    NOME VARCHAR(60),
    APELIDO VARCHAR(20),
    
    GENERO_ID CHAR(1),
    GENERO_DESCR NOME_CURTO_DOM,
    
    ESTADO_CIVIL_ID CHAR(1),
    ESTADO_CIVIL_DESCR NOME_CURTO_DOM,
    
    C VARCHAR(15),
    I VARCHAR(15),
    M VARCHAR(15),
    M_UF CHAR(2),
    
    EMAIL VARCHAR(50),
    DT_NASC DATE,
    ATIVO BOOLEAN,
    
    PESS_CRIADO_EM TIMESTAMP,
    PESS_ALTERADO_EM TIMESTAMP,
    
    LOGRADOURO VARCHAR(70),
    NUMERO NOME_DOM,
    COMPLEMENTO NOME_DOM,
    BAIRRO NOME_DOM,
    
    UF_SIGLA CHAR(2),
    CEP CHAR(8),
    
    MUNICIPIO_IBGE_ID CHAR(5),
    MUNICIPIO_NOME NOME_DOM,
    
    DDD CHAR(2),
    FONE1 NOME_CURTO_DOM,
    FONE2 NOME_CURTO_DOM,
    FONE3 NOME_CURTO_DOM,
    
    CONTATO NOME_DOM,
    REFERENCIA OBS1_DOM,
    
    ENDER_CRIADO_EM TIMESTAMP,
    ENDER_ALTERADO_EM TIMESTAMP,
    
    NOME_DE_USUARIO NOME_REDU_DOM,
    SENHA SENHA_DOM,
    CRY_VER ID_SHORT_DOM
  )
  AS
  BEGIN 
    FOR
      WITH ECIVIL AS (
        SELECT ESTADO_CIVIL_ID, DESCR FROM ESTADO_CIVIL
      ), MU AS(
         SELECT UF_SIGLA, MUNICIPIO_IBGE_ID, NOME FROM MUNICIPIO
      ), GEN AS (
        SELECT GENERO_ID, DESCR FROM GENERO
      ), PES AS (
        SELECT
          LOJA_ID, TERMINAL_ID, PESSOA_ID, NOME, APELIDO, GENERO_ID,
          ESTADO_CIVIL_ID, C, I, M, M_UF, EMAIL, DT_NASC, ATIVO,
          CRIADO_EM, ALTERADO_EM
        FROM
          PESSOA
        WHERE
          TERMINAL_ID = 0
      ), USU AS(
        SELECT LOJA_ID, TERMINAL_ID, PESSOA_ID, NOME_DE_USUARIO, SENHA,
        CRY_VER
        FROM USUARIO
      ), ENDER AS(
        SELECT
          LOJA_ID, TERMINAL_ID, PESSOA_ID, ORDEM, LOGRADOURO, NUMERO,
          COMPLEMENTO, BAIRRO, UF_SIGLA, CEP, MUNICIPIO_IBGE_ID,
          DDD, FONE1, FONE2, FONE3, CONTATO, REFERENCIA,
          CRIADO_EM, ALTERADO_EM
        FROM
          ENDERECO
        WHERE
          ORDEM = 0
      )
      SELECT
        PES.LOJA_ID,
        PES.TERMINAL_ID,
        PES.PESSOA_ID,
        
        PES.NOME,
        PES.APELIDO,
        
        GEN.GENERO_ID,
        GEN.DESCR GENERO_DESCR,
        
        ECIVIL.ESTADO_CIVIL_ID,
        ECIVIL.DESCR ESTADO_CIVIL_DESCR,
        
        PES.C,
        PES.I,
        PES.M,
        PES.M_UF,
        
        PES.EMAIL,
        PES.DT_NASC,
        PES.ATIVO,
        
        PES.CRIADO_EM PESS_CRIADO_EM,
        PES.ALTERADO_EM PESS_ALTERADO_EM,
        
        ENDER.LOGRADOURO,
        ENDER.NUMERO,
        ENDER.COMPLEMENTO,
        ENDER.BAIRRO,
        
        ENDER.UF_SIGLA,
        ENDER.CEP,
        
        ENDER.MUNICIPIO_IBGE_ID,
        MU.NOME MUNICIPIO_NOME,
        
        ENDER.DDD,
        ENDER.FONE1,
        ENDER.FONE2,
        ENDER.FONE3,
        
        ENDER.CONTATO,
        ENDER.REFERENCIA,
        
        ENDER.CRIADO_EM ENDER_CRIADO_EM,
        ENDER.ALTERADO_EM ENDER_ALTERADO_EM,
    
        USU.NOME_DE_USUARIO,
        USU.SENHA,
        USU.CRY_VER
      FROM PES

      LEFT JOIN ENDER ON 
      ENDER.LOJA_ID = PES.LOJA_ID
      AND ENDER.TERMINAL_ID = PES.TERMINAL_ID
      AND ENDER.PESSOA_ID = PES.PESSOA_ID

      LEFT JOIN MU ON ENDER.MUNICIPIO_IBGE_ID = MU.MUNICIPIO_IBGE_ID

      LEFT JOIN GEN ON
      GEN.GENERO_ID = PES.GENERO_ID

      LEFT JOIN ECIVIL ON
      ECIVIL.ESTADO_CIVIL_ID = PES.ESTADO_CIVIL_ID
      
      LEFT JOIN USU ON
      USU.LOJA_ID = PES.LOJA_ID
      AND USU.TERMINAL_ID = PES.TERMINAL_ID
      AND USU.PESSOA_ID = PES.PESSOA_ID 
    INTO 
      :LOJA_ID,
      :TERMINAL_ID,
      :PESSOA_ID,
      
      :NOME,
      :APELIDO,
      
      :GENERO_ID,
      :GENERO_DESCR,
      
      :ESTADO_CIVIL_ID,
      :ESTADO_CIVIL_DESCR,
      
      :C,
      :I,
      :M,
      :M_UF,
      
      :EMAIL,
      :DT_NASC,
      :ATIVO,
      
      :PESS_CRIADO_EM,
      :PESS_ALTERADO_EM ,
      
      :LOGRADOURO,
      :NUMERO,
      :COMPLEMENTO,
      :BAIRRO,
      
      :UF_SIGLA,
      :CEP,
      
      :MUNICIPIO_IBGE_ID,
      :MUNICIPIO_NOME,
      
      :DDD,
      :FONE1,
      :FONE2,
      :FONE3,
      
      :CONTATO,
      :REFERENCIA,
      
      :ENDER_CRIADO_EM,
      :ENDER_ALTERADO_EM,
      
      :NOME_DE_USUARIO,
      :SENHA,
      :CRY_VER
    DO 
      SUSPEND;
  END
END^
SET TERM ;^
