SET TERM ^;
CREATE OR ALTER PACKAGE FUNCIONARIO_PA
AS
BEGIN
  PROCEDURE GARANTIR_NOMES
  (
    LOJA_ID ID_SHORT_DOM NOT NULL,
    NOME NOME_DOM NOT NULL,
    APELIDO VARCHAR(20) NOT NULL,

    LOG_PESSOA_ID ID_DOM,
    MACHINE_ID ID_SHORT_DOM,
    FUNCIONARIO_PESSOA_ID ID_DOM
)
  RETURNS
  (
    PESSOA_ID_RET INTEGER 
  );

  PROCEDURE GARANTIR
  (
    LOJA_ID SMALLINT NOT NULL,
    TERMINAL_ID SMALLINT NOT NULL,

    NOME VARCHAR(60),
    APELIDO VARCHAR(20),
    NOME_FANTASIA VARCHAR(60),
    GENERO_ID CHAR(1),
    ESTADO_CIVIL_ID CHAR(1),
    C VARCHAR(15),
    I VARCHAR(15),
    M VARCHAR(15),
    M_UF CHAR(2),
    EMAIL VARCHAR(50),
    DT_NASC DATE,
    ATIVO BOOLEAN,

    LOGRADOURO        VARCHAR(70),
    NUMERO            NOME_DOM,
    COMPLEMENTO       NOME_DOM,
    BAIRRO            NOME_DOM,
    UF_SIGLA          CHAR(2),
    CEP               CHAR(8),
    MUNICIPIO_IBGE_ID CHAR(7),
    DDD               CHAR(2),
    FONE1             NOME_CURTO_DOM,
    FONE2             NOME_CURTO_DOM,
    FONE3             NOME_CURTO_DOM,
    CONTATO           NOME_DOM,
    REFERENCIA        OBS1_DOM,
    
    LOG_PESSOA_ID ID_DOM,
    MACHINE_ID ID_SHORT_DOM,
    FUNCIONARIO_PESSOA_ID ID_DOM
  )
  RETURNS
  (
    LOJA_ID_RET SMALLINT,
    TERMINAL_ID_RET SMALLINT,
    PESSOA_ID_RET INTEGER
  );
END^

RECREATE PACKAGE BODY FUNCIONARIO_PA
AS
BEGIN
  PROCEDURE GARANTIR_NOMES
  (
    LOJA_ID ID_SHORT_DOM NOT NULL,
    NOME NOME_DOM NOT NULL,
    APELIDO VARCHAR(20) NOT NULL,

    LOG_PESSOA_ID ID_DOM,
    MACHINE_ID ID_SHORT_DOM,
    FUNCIONARIO_PESSOA_ID ID_DOM
  )
  RETURNS
  (
    PESSOA_ID_RET  INTEGER 
  )
  AS
    -- FUNCIONARIO GAR NOMES LOGVAR LOGVARS VARS LOG VAR LOG VARLOG VARSLOG
    DECLARE FEATURE_ID ID_SHORT_DOM = 3;--FUNCIONARIO
    DECLARE RETAGUARDA_TERMINAL_ID ID_SHORT_DOM = 0;
    DECLARE RETAGUARDA_MODULO_ID ID_CHAR_DOM = '"';
    DECLARE ACAO_SIS_ID ID_CHAR_DOM = '''';--GARANTIR
    DECLARE LOG_ID_RET BIGINT;
BEGIN
    EXECUTE PROCEDURE PESSOA_PA.GARANTIR_NOMES(:LOJA_ID, 0, :NOME, :APELIDO, :FUNCIONARIO_PESSOA_ID)
      RETURNING_VALUES :PESSOA_ID_RET;
    
    UPDATE OR INSERT INTO FUNCIONARIO (LOJA_ID, TERMINAL_ID, PESSOA_ID)
    VALUES (:LOJA_ID, 0, :PESSOA_ID_RET)
    MATCHING (LOJA_ID, TERMINAL_ID, PESSOA_ID);
    
    SUSPEND; -- RETORNA O VALOR DE PESSOA_ID_RET

    SELECT LOG_ID_RET 
    FROM LOG_PA.LOG_NOVO_GET
    (
      :LOJA_ID,
      :RETAGUARDA_TERMINAL_ID,
      :LOG_PESSOA_ID,
      :RETAGUARDA_MODULO_ID,
      :ACAO_SIS_ID,
      :FEATURE_ID,
      :MACHINE_ID
    ) INTO :LOG_ID_RET;

    EXECUTE PROCEDURE LOG_PA.LOG_ENVOLVE_ID_INS
    (
      :LOJA_ID,
      :RETAGUARDA_TERMINAL_ID,
      :LOG_ID_RET,
      0,

      0, --LOJA_ID_ENVOLVIDO SMALLINT,
      0, --TERMINAL_ID_ENVOLVIDO SMALLINT,
      :PESSOA_ID_RET, --ID_ENVOLVIDO BIGINT,
      0 --ORDEM_ENVOLVIDO SMALLINT
    );
  END

  PROCEDURE GARANTIR
  (
    LOJA_ID SMALLINT NOT NULL,
    TERMINAL_ID SMALLINT NOT NULL,
    NOME VARCHAR(60),
    APELIDO VARCHAR(20),
    NOME_FANTASIA VARCHAR(60),
    GENERO_ID CHAR(1),
    ESTADO_CIVIL_ID CHAR(1),
    C VARCHAR(15),
    I VARCHAR(15),
    M VARCHAR(15),
    M_UF CHAR(2),
    EMAIL VARCHAR(50),
    DT_NASC DATE,
    ATIVO BOOLEAN,
    
    LOGRADOURO        VARCHAR(70),
    NUMERO            NOME_DOM,
    COMPLEMENTO       NOME_DOM,
    BAIRRO            NOME_DOM,
    UF_SIGLA          CHAR(2),
    CEP               CHAR(8),
    MUNICIPIO_IBGE_ID CHAR(7),
    DDD               CHAR(2),
    FONE1             NOME_CURTO_DOM,
    FONE2             NOME_CURTO_DOM,
    FONE3             NOME_CURTO_DOM,
    CONTATO           NOME_DOM,
    REFERENCIA        OBS1_DOM,

    LOG_PESSOA_ID ID_DOM,
    MACHINE_ID ID_SHORT_DOM,
    FUNCIONARIO_PESSOA_ID ID_DOM
  )
  RETURNS
  (
    LOJA_ID_RET SMALLINT,
    TERMINAL_ID_RET SMALLINT,
    PESSOA_ID_RET INTEGER
  )
  AS
    -- FUNCIONARIO GAR LOGVAR LOGVARS VARS LOG VAR LOG VARLOG VARSLOG
    DECLARE FEATURE_ID ID_SHORT_DOM = 3;--FUNCIONARIO
    DECLARE RETAGUARDA_TERMINAL_ID ID_SHORT_DOM = 0;
    DECLARE RETAGUARDA_MODULO_ID ID_CHAR_DOM = '"';
    DECLARE ACAO_SIS_ID ID_CHAR_DOM = '''';--GARANTIR
    DECLARE LOG_ID_RET BIGINT;
  BEGIN
    EXECUTE PROCEDURE PESSOA_PA.GARANTIR(
      :LOJA_ID,
      :TERMINAL_ID,
      :NOME,
      :NOME_FANTASIA,
      :APELIDO,
      :GENERO_ID,
      :ESTADO_CIVIL_ID,
      :C,
      :I,
      :M,
      :M_UF,
      :EMAIL,
      :DT_NASC,
      :ATIVO,
      :FUNCIONARIO_PESSOA_ID,
      :LOGRADOURO,
      :NUMERO,
      :COMPLEMENTO,
      :BAIRRO,
      :UF_SIGLA,
      :CEP,
      :MUNICIPIO_IBGE_ID,
      :DDD,
      :FONE1,
      :FONE2,
      :FONE3,
      :CONTATO,
      :REFERENCIA
    )
    RETURNING_VALUES :PESSOA_ID_RET;

    UPDATE OR INSERT INTO FUNCIONARIO (LOJA_ID, TERMINAL_ID, PESSOA_ID)
    VALUES (:LOJA_ID, :TERMINAL_ID, :PESSOA_ID_RET)
    MATCHING (LOJA_ID, TERMINAL_ID, PESSOA_ID);

    :LOJA_ID_RET = :LOJA_ID;
    :TERMINAL_ID_RET = :TERMINAL_ID;
    
    SUSPEND;

    SELECT LOG_ID_RET 
    FROM LOG_PA.LOG_NOVO_GET
    (
      :LOJA_ID,
      :RETAGUARDA_TERMINAL_ID,
      :LOG_PESSOA_ID,
      :RETAGUARDA_MODULO_ID,
      :ACAO_SIS_ID,
      :FEATURE_ID,
      :MACHINE_ID
    ) INTO :LOG_ID_RET;

    EXECUTE PROCEDURE LOG_PA.LOG_ENVOLVE_ID_INS
    (
      :LOJA_ID,
      :RETAGUARDA_TERMINAL_ID,
      :LOG_ID_RET,
      0,

      0, --LOJA_ID_ENVOLVIDO SMALLINT,
      0, --TERMINAL_ID_ENVOLVIDO SMALLINT,
      :PESSOA_ID_RET, --ID_ENVOLVIDO BIGINT,
      0 --ORDEM_ENVOLVIDO SMALLINT
    );
  END
END^
SET TERM ;^
