SET TERM ^;
CREATE OR ALTER PACKAGE LOJA_MANUT_PA
AS
BEGIN
  PROCEDURE GARANTIR(
    LOJA_ID SMALLINT NOT NULL,
    TERMINAL_ID SMALLINT NOT NULL,
    
    NOME VARCHAR(60),
    NOME_FANTASIA VARCHAR(60),
    APELIDO VARCHAR(20),
    
    GENERO_ID CHAR(1),
    ESTADO_CIVIL_ID CHAR(1),
    
    C VARCHAR(15),
    I VARCHAR(15),
    M VARCHAR(15),
    M_UF CHAR(2),
    
    EMAIL VARCHAR(50),
    DT_NASC DATE,
    ATIVO BOOLEAN,
    
    PESSOA_ID INTEGER,

    LOGRADOURO        VARCHAR(70),
    NUMERO            NOME_DOM,
    COMPLEMENTO       NOME_DOM,
    BAIRRO            NOME_DOM,
    
    UF_SIGLA          CHAR(2),
    CEP               CHAR(8),
    MUNICIPIO_IBGE_ID CHAR(7),
    
    DDD               CHAR(2),
    FONE1             NOME_CURTO_DOM,
    FONE2             NOME_CURTO_DOM,
    FONE3             NOME_CURTO_DOM,
    
    CONTATO           NOME_DOM,
    REFERENCIA        OBS1_DOM
    
    , SELECIONADO BOOLEAN

    , LOG_LOJA_ID ID_DOM NOT NULL
    , LOG_PESSOA_ID ID_DOM NOT NULL
    , MACHINE_ID ID_SHORT_DOM
)
  RETURNS
  (
    LOJA_ID_RET SMALLINT,
    TERMINAL_ID_RET SMALLINT,
    PESSOA_ID_RET INTEGER
  );
END^

----- body -----

RECREATE PACKAGE BODY LOJA_MANUT_PA
AS
BEGIN
  PROCEDURE GARANTIR(
    LOJA_ID SMALLINT NOT NULL,
    TERMINAL_ID SMALLINT NOT NULL,

    NOME VARCHAR(60),
    NOME_FANTASIA VARCHAR(60),
    APELIDO VARCHAR(20),

    GENERO_ID CHAR(1),
    ESTADO_CIVIL_ID CHAR(1),

    C VARCHAR(15),
    I VARCHAR(15),
    M VARCHAR(15),
    M_UF CHAR(2),

    EMAIL VARCHAR(50),
    DT_NASC DATE,
    ATIVO BOOLEAN,

    PESSOA_ID INTEGER,

    LOGRADOURO        VARCHAR(70),
    NUMERO            NOME_DOM,
    COMPLEMENTO       NOME_DOM,
    BAIRRO            NOME_DOM,

    UF_SIGLA          CHAR(2),
    CEP               CHAR(8),
    MUNICIPIO_IBGE_ID CHAR(7),

    DDD               CHAR(2),
    FONE1             NOME_CURTO_DOM,
    FONE2             NOME_CURTO_DOM,
    FONE3             NOME_CURTO_DOM,

    CONTATO           NOME_DOM,
    REFERENCIA        OBS1_DOM

    , SELECIONADO BOOLEAN

    , LOG_LOJA_ID ID_DOM NOT NULL
    , LOG_PESSOA_ID ID_DOM NOT NULL
    , MACHINE_ID ID_SHORT_DOM

  )
  RETURNS
  (
    LOJA_ID_RET SMALLINT,
    TERMINAL_ID_RET SMALLINT,
    PESSOA_ID_RET INTEGER
  )
  AS
  BEGIN
    SELECT PESSOA_ID_GRAVADA FROM PESSOA_PA.GARANTIR(
      :LOJA_ID,
      :TERMINAL_ID,
      :NOME,
      :NOME_FANTASIA,
      :APELIDO,
      :GENERO_ID,
      :ESTADO_CIVIL_ID,
      :C,
      :I,
      :M,
      :M_UF,
      :EMAIL,
      :DT_NASC,
      :ATIVO,
      :PESSOA_ID,
      :LOGRADOURO,
      :NUMERO,
      :COMPLEMENTO,
      :BAIRRO,
      :UF_SIGLA,
      :CEP,
      :MUNICIPIO_IBGE_ID,
      :DDD,
      :FONE1,
      :FONE2,
      :FONE3,
      :CONTATO,
      :REFERENCIA
    ) INTO :PESSOA_ID_RET;

    :LOJA_ID_RET = :LOJA_ID;
    :TERMINAL_ID_RET = :TERMINAL_ID;
    
    IF (:SELECIONADO IS NULL) THEN
    BEGIN
      :SELECIONADO = FALSE;
    END
    ELSE IF (:SELECIONADO = TRUE) THEN
    BEGIN
      UPDATE LOJA SET SELECIONADO = FALSE;
    END
    
    SUSPEND;
  END
END^
SET TERM ;^
