SET TERM ^;
CREATE OR ALTER PACKAGE PERFIL_DE_USO_PA
AS
BEGIN
  PROCEDURE GARANTIR
  (
    PERFIL_DE_USO_ID ID_SHORT_DOM NOT NULL
    , NOME NOME_REDU_DOM NOT NULL
    , DE_SISTEMA BOOLEAN NOT NULL
  )
    RETURNS
  (
    ID_GRAVADO ID_SHORT_DOM
  );
  
  PROCEDURE LISTA_GET
  RETURNS 
  (
    PERFIL_DE_USO_ID ID_SHORT_DOM,
    NOME NOME_REDU_DOM,
    DE_SISTEMA BOOLEAN,
    USUARIOS_APELIDOS VARCHAR(1024)
  );

  PROCEDURE BYNOME_GET 
  (
    NOME NOME_REDU_DOM
  )
  RETURNS 
  (
    PERFIL_DE_USO_ID ID_SHORT_DOM,
    DE_SISTEMA BOOLEAN
  );

  PROCEDURE PODE_NADA_SET 
  (
    PERFIL_DE_USO_ID ID_SHORT_DOM NOT NULL
  );
  
  PROCEDURE PERFIL_DE_USO_PODE_OPCAO_SIS_GAR 
  (
    PERFIL_DE_USO_ID ID_SHORT_DOM NOT NULL,
    OPCAO_SIS_ID ID_DOM NOT NULL
  );
  
  PROCEDURE PERFIL_DE_USO_PODE_OPCOES_GAR
  (
    PERFIL_DE_USO_ID ID_SHORT_DOM,
    STR_OPCOES_ID VARCHAR(15000)
  );
  
END^

----- BODY -----

RECREATE PACKAGE BODY PERFIL_DE_USO_PA
AS
BEGIN
  PROCEDURE GARANTIR
  (
    PERFIL_DE_USO_ID ID_SHORT_DOM NOT NULL
    , NOME NOME_REDU_DOM NOT NULL
    , DE_SISTEMA BOOLEAN NOT NULL
  )
    RETURNS
  (
    ID_GRAVADO ID_SHORT_DOM
  )
  AS
  BEGIN
    IF (PERFIL_DE_USO_ID < 1) THEN
    BEGIN
      ID_GRAVADO = NEXT VALUE FOR PERFIL_DE_USO_SEQ;
    END
    ELSE
    BEGIN
      ID_GRAVADO = PERFIL_DE_USO_ID;
    END	
	
    UPDATE OR INSERT INTO PERFIL_DE_USO (PERFIL_DE_USO_ID, NOME, DE_SISTEMA)
    VALUES (:ID_GRAVADO, :NOME, :DE_SISTEMA)
    MATCHING (PERFIL_DE_USO_ID);
  END

  PROCEDURE LISTA_GET
  RETURNS (
    PERFIL_DE_USO_ID ID_SHORT_DOM,
    NOME NOME_REDU_DOM,
    DE_SISTEMA BOOLEAN,
    USUARIOS_APELIDOS varchar(1024)
  )
  AS
  BEGIN
    FOR
    WITH 
      PES AS (
        SELECT 
          LOJA_ID, TERMINAL_ID, PESSOA_ID, APELIDO
        FROM 
          PESSOA
        WHERE 
          ATIVO = TRUE
      ),
      U AS (
        SELECT 
          LOJA_ID, TERMINAL_ID, PESSOA_ID
        FROM 
          USUARIO
      ),
      UTPER AS (
        SELECT 
          LOJA_ID, TERMINAL_ID, PESSOA_ID, PERFIL_DE_USO_ID
        FROM 
          USUARIO_TEM_PERFIL_DE_USO
      ),
      PER AS (
        SELECT 
          PERFIL_DE_USO_ID, NOME, DE_SISTEMA
        FROM 
          PERFIL_DE_USO
      )
    SELECT 
      PER.PERFIL_DE_USO_ID,
      PER.NOME,
      PER.DE_SISTEMA,
      LIST(PES.APELIDO, ', ') AS USUARIOS_APELIDOS
    FROM 
      PER
    JOIN 
      UTPER ON PER.PERFIL_DE_USO_ID = UTPER.PERFIL_DE_USO_ID
    JOIN 
      U ON UTPER.LOJA_ID = U.LOJA_ID AND UTPER.TERMINAL_ID = U.TERMINAL_ID AND UTPER.PESSOA_ID = U.PESSOA_ID
    JOIN 
      PES ON U.LOJA_ID = PES.LOJA_ID AND U.TERMINAL_ID = PES.TERMINAL_ID AND U.PESSOA_ID = PES.PESSOA_ID
    GROUP BY 
      PER.PERFIL_DE_USO_ID, PER.NOME, PER.DE_SISTEMA
    INTO 
      :PERFIL_DE_USO_ID, :NOME, :DE_SISTEMA, :USUARIOS_APELIDOS
    DO
    BEGIN
      SUSPEND;
    END
  END

  PROCEDURE BYNOME_GET
  (
    NOME NOME_REDU_DOM
  )
  RETURNS 
  (
    PERFIL_DE_USO_ID ID_SHORT_DOM,
    DE_SISTEMA BOOLEAN
  )
  AS
  BEGIN
    FOR SELECT PERFIL_DE_USO_ID, DE_SISTEMA
      FROM PERFIL_DE_USO
      WHERE NOME = :NOME
        INTO :PERFIL_DE_USO_ID, :DE_SISTEMA
      DO
        SUSPEND;
  END
  
  PROCEDURE PODE_NADA_SET 
  (
    PERFIL_DE_USO_ID ID_SHORT_DOM NOT NULL
  )
  AS
  BEGIN
    DELETE FROM PERFIL_DE_USO_PODE_OPCAO_SIS WHERE PERFIL_DE_USO_ID = :PERFIL_DE_USO_ID;
  END
  
  PROCEDURE PERFIL_DE_USO_PODE_OPCAO_SIS_GAR 
  (
    PERFIL_DE_USO_ID ID_SHORT_DOM NOT NULL,
    OPCAO_SIS_ID ID_DOM NOT NULL
  )
  AS
  BEGIN
    UPDATE OR INSERT INTO PERFIL_DE_USO_PODE_OPCAO_SIS (PERFIL_DE_USO_ID, OPCAO_SIS_ID)
    VALUES (:PERFIL_DE_USO_ID, :OPCAO_SIS_ID);
  END
  
  
  PROCEDURE PERFIL_DE_USO_PODE_OPCOES_GAR
  (
    PERFIL_DE_USO_ID ID_SHORT_DOM,
    STR_OPCOES_ID VARCHAR(15000)
  )
  AS
    DECLARE VARIABLE OPCAO_SIS_ID_STR CHAR(11);
    DECLARE VARIABLE OPCAO_SIS_ID ID_DOM;
    DECLARE VARIABLE POSICAO INTEGER;
    
  BEGIN
    EXECUTE PROCEDURE PODE_NADA_SET(PERFIL_DE_USO_ID);
    --DELETE FROM PERFIL_DE_USO_PODE_OPCAO_SIS WHERE PERFIL_DE_USO_ID = :PERFIL_DE_USO_ID;

    WHILE (STR_OPCOES_ID <> '') DO
    BEGIN
      POSICAO = POSITION(';' IN STR_OPCOES_ID);
      
      IF (POSICAO = 0) THEN
      BEGIN
        OPCAO_SIS_ID_STR = TRIM(STR_OPCOES_ID);
        STR_OPCOES_ID = '';
      END
      ELSE
      BEGIN
        OPCAO_SIS_ID_STR = TRIM(SUBSTRING(STR_OPCOES_ID FROM 1 FOR POSICAO - 1));
        STR_OPCOES_ID = SUBSTRING(STR_OPCOES_ID FROM POSICAO + 1);
      END
      
      IF (OPCAO_SIS_ID_STR <> '') THEN
      BEGIN
        OPCAO_SIS_ID = CAST(OPCAO_SIS_ID_STR AS ID_DOM);
        
        INSERT INTO PERFIL_DE_USO_PODE_OPCAO_SIS (PERFIL_DE_USO_ID, OPCAO_SIS_ID) 
        VALUES(:PERFIL_DE_USO_ID, :OPCAO_SIS_ID);
      END
    END
  END
  
END^
SET TERM ;^
