SET TERM ^;
CREATE OR ALTER PACKAGE PERFIL_USO_PA
AS
BEGIN
  PROCEDURE GARANTIR
  (
    PERFIL_USO_ID ID_SHORT_NOTN_DOM
    , NOME NOME_REDU_NOTN_DOM
    , DE_SISTEMA BOOLEAN NOT NULL
  )
    RETURNS
  (
    ID_GRAVADO SMALLINT
  );
  
  PROCEDURE PERFIL_USO_ACESSA_MODULO_GARANTIR(
    PERFIL_USO_ID ID_SHORT_NOTN_DOM
    , MODULO_ID ID_CHAR_NOTN_DOM
  );

  PROCEDURE PERFIL_USO_MODULOS_GET
  (
    PERFIL_USO_ID ID_SHORT_NOTN_DOM
  )
  RETURNS
  (
    MODULO_ID CHAR
    , DESCR NOME_CURTO_DOM
  );

  PROCEDURE LISTA_GET
  RETURNS 
  (
      PERFIL_USO_ID ID_SHORT_DOM,
      NOME NOME_REDU_NOTN_DOM,
      DE_SISTEMA BOOLEAN
  );

END^

----- body -----

RECREATE PACKAGE BODY PERFIL_USO_PA
AS
BEGIN
  PROCEDURE GARANTIR
  (
    PERFIL_USO_ID ID_SHORT_NOTN_DOM
    , NOME NOME_REDU_NOTN_DOM
    , DE_SISTEMA BOOLEAN NOT NULL
  )
    RETURNS
  (
    ID_GRAVADO SMALLINT
  )
  AS
  BEGIN
    IF (PERFIL_USO_ID < 1) THEN
    BEGIN
      ID_GRAVADO = NEXT VALUE FOR PERFIL_USO_SEQ;
    END
    ELSE
    BEGIN
      ID_GRAVADO = PERFIL_USO_ID;
    END	
	
    UPDATE OR INSERT INTO PERFIL_USO (PERFIL_USO_ID, NOME, DE_SISTEMA)
    VALUES (:ID_GRAVADO, :NOME, :DE_SISTEMA)
    MATCHING (PERFIL_USO_ID);
  END

  PROCEDURE PERFIL_USO_ACESSA_MODULO_GARANTIR(
    PERFIL_USO_ID ID_SHORT_NOTN_DOM
    , MODULO_ID ID_CHAR_NOTN_DOM
  )
  AS
  BEGIN
    UPDATE OR INSERT INTO PERFIL_USO_ACESSA_MODULO (PERFIL_USO_ID, MODULO_ID)
    VALUES (:PERFIL_USO_ID, :MODULO_ID)
    MATCHING (PERFIL_USO_ID, MODULO_ID);
  END

  PROCEDURE PERFIL_USO_MODULOS_GET(PERFIL_USO_ID ID_SHORT_NOTN_DOM)
  RETURNS (MODULO_ID CHAR, DESCR NOME_CURTO_DOM)
  AS 
  BEGIN 
    FOR SELECT M.MODULO_ID, M.DESCR
    FROM MODULO M
    JOIN PERFIL_USO_ACESSA_MODULO P ON P.MODULO_ID = M.MODULO_ID
    WHERE P.PERFIL_USO_ID = :PERFIL_USO_ID
    INTO :MODULO_ID, :DESCR
    DO SUSPEND; 
  END
  
  PROCEDURE LISTA_GET
  RETURNS (
    PERFIL_USO_ID ID_SHORT_DOM,
    NOME NOME_REDU_NOTN_DOM,
    DE_SISTEMA BOOLEAN
  )
  AS
  BEGIN
    FOR SELECT PERFIL_USO_ID, NOME, DE_SISTEMA FROM perfil_uso
    INTO :PERFIL_USO_ID, :NOME, :DE_SISTEMA
    DO
    BEGIN
      SUSPEND;
    END
  END
  
END^
SET TERM ;^
