DROP TABLE USU;

CREATE TABlE USU
(
USU_ID INTEGER NOT NULL
, NOME_USU VARCHAR(32)
, NOME_EXIB VARCHAR(32)
, SENHA VARCHAR(32)
);

ALTER TABLE USU
ADD CONSTRAINT USU_PK
PRIMARY KEY (USU_ID);

CREATE GENERATOR USU_G;
--SET GENERATOR PROD_CATEG_G TO 3;
--SELECT NEXT VALUE FOR PROD_CATEG_G FROM RDB$DATABASE;

INSERT INTO PROD_CATEG(PROD_CATEG_ID,NOME) VALUES (1, 'LIMPEZA');
INSERT INTO PROD_CATEG(PROD_CATEG_ID,NOME) VALUES (2, 'MATINAIS');
INSERT INTO PROD_CATEG(PROD_CATEG_ID,NOME) VALUES (3, 'GRAOS');
COMMIT;


