SET TERM ^;
CREATE OR ALTER PACKAGE SERV_ENV_DADOS_PA
AS
BEGIN
  PROCEDURE QTD_REGS_GET
  RETURNS 
  (
    QTD_REGS INTEGER
  );
END^

---------------------------
---    BODY
---------------------------

RECREATE PACKAGE BODY SERV_ENV_DADOS_PA
AS
BEGIN
  PROCEDURE QTD_REGS_GET
  RETURNS 
  (
    QTD_REGS INTEGER
  )
  AS
  DECLARE VARIABLE QTD INTEGER;
  BEGIN
    QTD_REGS = 0;

    SELECT COUNT(*) FROM PESSOA INTO :QTD;
    QTD_REGS = QTD_REGS + :QTD;

    SELECT COUNT(*) FROM TERMINAL INTO :QTD;
    QTD_REGS = QTD_REGS + :QTD;

    SELECT COUNT(*) FROM PROD INTO :QTD;
    QTD_REGS = QTD_REGS + :QTD;

    SELECT COUNT(*) FROM PROD_BARRAS INTO :QTD;
    QTD_REGS = QTD_REGS + :QTD;
  END
END^
SET TERM ;^
