SET TERM ^;
CREATE OR ALTER PACKAGE IMPORT_FABR_PA
AS
BEGIN
  PROCEDURE GARANTIR_ID_DESCR
  (
    NOME NOME_REDU_DOM NOT NULL, 
    FABR_ID ID_SHORT_DOM
  )
  RETURNS
  (
    IMPORT_FABR_ID ID_DOM
  );
  
  PROCEDURE APAGAR_DO;
END^

----- body -----

RECREATE PACKAGE BODY IMPORT_FABR_PA
AS
BEGIN
  PROCEDURE GARANTIR_ID_DESCR
  (
    NOME NOME_REDU_DOM NOT NULL,
    FABR_ID ID_SHORT_DOM
  )
  RETURNS 
  (
    IMPORT_FABR_ID ID_DOM
  )
  AS
  BEGIN
    SELECT IMPORT_FABR_ID FROM IMPORT_FABR WHERE NOME = :NOME INTO :IMPORT_FABR_ID;
    
    IF (IMPORT_FABR_ID IS NOT NULL) THEN
    BEGIN
      UPDATE IMPORT_FABR SET FABR_ID = :FABR_ID WHERE IMPORT_FABR_ID = :IMPORT_FABR_ID;
    END
    ELSE
    BEGIN
      IMPORT_FABR_ID = NEXT VALUE FOR IMPORT_FABR_SEQ;
      INSERT INTO IMPORT_FABR (IMPORT_FABR_ID, NOME, FABR_ID) VALUES (:IMPORT_FABR_ID, :NOME, :FABR_ID);
    END
    SUSPEND;
  END
  
  PROCEDURE APAGAR_DO
  AS
  BEGIN
    EXECUTE STATEMENT('ALTER SEQUENCE IMPORT_FABR_SEQ RESTART WITH  1;');
    DELETE FROM IMPORT_FABR;
  END
END^
SET TERM ;^
