SELECT FORMA_ID,DESCR FROM CAIXA_SESSAO_PDV_PA.SESS_RELAT_PAGFORMA_LISTA_GET;

SELECT FORMA_ID,TOTAL FROM CAIXA_SESSAO_PDV_PA.SESS_VENDA_PAG_TOTAL_GET(1,1,1);

SELECT

SELECT 
  F.FORMA_ID
  , F.DESCR
  , P.TOTAL PAG_TOTAL
  , COALESCE(D.TOTAL, 0) DIGITADO
  , P.TOTAL - COALESCE(D.TOTAL, 0) DIF
FROM CAIXA_SESSAO_PDV_PA.SESS_RELAT_PAGFORMA_LISTA_GET F
JOIN CAIXA_SESSAO_PDV_PA.SESS_VENDA_PAG_TOTAL_GET(1,1,1) P ON
F.FORMA_ID = P.FORMA_ID
LEFT JOIN CAIXA_SESSAO_PDV_PA.SESS_RELAT_FECH_TOTAIS_GET(1,1,1) D ON
F.FORMA_ID = D.FORMA_ID
ORDER BY F.FORMA_ID

SELECT *  FROM CAIXA_SESSAO_PDV_PA.SESS_RELAT_FECH_TOTAIS_GET(1,1,1);


  