SELECT 
  T.NAME
  , T.SINAL_NUMERICO
  , SUM(V.VALOR) AS TOTAL

FROM CAIXA_SESSAO_OPERACAO_TIPO T

JOIN CAIXA_SESSAO_OPERACAO O ON
T.OPER_TIPO_ID = O.OPER_TIPO_ID

JOIN CAIXA_SESSAO_OPERACAO_VALOR V ON
O.LOJA_ID = V.LOJA_ID
AND O.TERMINAL_ID = V.TERMINAL_ID
AND O.SESS_ID = V.SESS_ID
AND O.OPER_ORDEM = V.OPER_ORDEM

WHERE NOT O.CANCELADO
AND O.OPER_TIPO_ID <> '('

GROUP BY 
  O.OPER_TIPO_ID
  , T.NAME
  , T.SINAL_NUMERICO
