SET TERM ^;
CREATE OR ALTER PACKAGE LOG_PA
AS
BEGIN
  PROCEDURE LOG_NOVO_GET
  (
    LOJA_ID ID_SHORT_DOM NOT NULL,
    TERMINAL_ID ID_SHORT_DOM NOT NULL,

    PESSOA_ID ID_DOM NOT NULL,
    MODULO_ID ID_CHAR_DOM NOT NULL,
    ACAO_SIS_ID ID_CHAR_DOM NOT NULL,
    FEATURE_ID ID_SHORT_DOM NOT NULL,
    MACHINE_ID ID_SHORT_DOM NOT NULL
  ) 
  RETURNS 
  (
    LOG_ID_RET BIGINT
    , DTH TIMESTAMP
  );

  PROCEDURE LOG_ENVOLVE_ID_INS
  (
    LOJA_ID SMALLINT,
    TERMINAL_ID SMALLINT,
    LOG_ID BIGINT,
    ORDEM SMALLINT,

    LOJA_ID_ENVOLVIDO SMALLINT,
    TERMINAL_ID_ENVOLVIDO SMALLINT,
    ID_ENVOLVIDO BIGINT,
    ORDEM_ENVOLVIDO SMALLINT
  );

END^

RECREATE PACKAGE BODY LOG_PA
AS
BEGIN
  PROCEDURE LOG_NOVO_GET
  (
    LOJA_ID ID_SHORT_DOM NOT NULL,
    TERMINAL_ID ID_SHORT_DOM NOT NULL,

    PESSOA_ID ID_DOM NOT NULL,
    MODULO_ID ID_CHAR_DOM NOT NULL,
    ACAO_SIS_ID ID_CHAR_DOM NOT NULL,
    FEATURE_ID ID_SHORT_DOM NOT NULL,
    MACHINE_ID ID_SHORT_DOM NOT NULL
  ) 
  RETURNS 
  (
    LOG_ID_RET BIGINT
    , DTH TIMESTAMP
  ) 
  AS 
  BEGIN
    LOG_ID_RET = NEXT VALUE FOR LOG_SEQ;

    INSERT INTO LOG
    (
      LOJA_ID, TERMINAL_ID, LOG_ID,

      PESSOA_ID,
      MODULO_ID,
      ACAO_SIS_ID,
      
      FEATURE_ID,
      MACHINE_ID
    )
    VALUES
    (
      :LOJA_ID,
      :TERMINAL_ID,
      :LOG_ID_RET,

      :PESSOA_ID,
      :MODULO_ID,
      :ACAO_SIS_ID,
      
      :FEATURE_ID,
      :MACHINE_ID
    ) 
    RETURNING DTH INTO :DTH;
    SUSPEND;
  END

  PROCEDURE LOG_ENVOLVE_ID_INS
  (
    LOJA_ID SMALLINT,
    TERMINAL_ID SMALLINT,
    LOG_ID BIGINT,
    ORDEM SMALLINT,

    LOJA_ID_ENVOLVIDO SMALLINT,
    TERMINAL_ID_ENVOLVIDO SMALLINT,
    ID_ENVOLVIDO BIGINT,
    ORDEM_ENVOLVIDO SMALLINT
  )
  AS
  BEGIN
    INSERT INTO LOG_ENVOLVE_ID 
    (
      LOJA_ID,
      TERMINAL_ID,
      LOG_ID,
      ORDEM,

      LOJA_ID_ENVOLVIDO,
      TERMINAL_ID_ENVOLVIDO,
      ID_ENVOLVIDO,
      ORDEM_ENVOLVIDO
    )
    VALUES (
      :LOJA_ID,
      :TERMINAL_ID,
      :LOG_ID,
      :ORDEM,

      :LOJA_ID_ENVOLVIDO,
      :TERMINAL_ID_ENVOLVIDO,
      :ID_ENVOLVIDO,
      :ORDEM_ENVOLVIDO
    );
  END
END^
SET TERM ;^
