SET TERM ^;
CREATE OR ALTER PACKAGE EST_STAT_PA
AS
BEGIN
  PROCEDURE STAT_GET
  RETURNS
  (
      PROD_RECORD_COUNT_RET INTEGER
  );
END^

----- body -----
--SELECT * FROM EST_STAT_PA.STAT_GET;
RECREATE PACKAGE BODY EST_STAT_PA
AS
BEGIN
  PROCEDURE STAT_GET
  RETURNS
  (
      PROD_RECORD_COUNT_RET INTEGER
  )
  AS
  BEGIN
    SELECT RECORD_COUNT FROM PROD_PA.PROD_RECORD_COUNT_GET INTO :PROD_RECORD_COUNT_RET;
    SUSPEND;
  END
END^
SET TERM ;^
