SET TERM ^;
CREATE OR ALTER PACKAGE CAIXA_SESSAO_MANUT_PA
AS
BEGIN
  PROCEDURE ABERTO_GET
  RETURNS
  (
    CAIXA_SESSAO_ID ID_DOM
    , LOG_ID BIGINT
    , PESSOA_ID ID_DOM
    , APELIDO NOME_REDU_DOM
  );

END^

RECREATE PACKAGE BODY CAIXA_SESSAO_MANUT_PA
AS
BEGIN
  PROCEDURE ABERTO_GET
  RETURNS
  (
    CAIXA_SESSAO_ID ID_DOM
    , LOG_ID BIGINT
    , PESSOA_ID ID_DOM
    , APELIDO NOME_REDU_DOM
  )
  AS
  BEGIN
    FOR
      SELECT
      SESS.CAIXA_SESSAO_ID
      , SESS.LOG_ID
      , PESS.PESSOA_ID
      , PESS.APELIDO
      
      FROM AMBIENTE_SIS AMBI  

      JOIN CAIXA_SESSAO SESS ON
      AMBI.LOJA_ID = SESS.LOJA_ID
      AND AMBI.TERMINAL_ID = SESS.TERMINAL_ID

      JOIN LOG ON
      SESS.LOJA_ID = LOG.LOJA_ID
      AND SESS.TERMINAL_ID = LOG.TERMINAL_ID 
      AND SESS.LOG_ID = LOG.LOG_ID 

      JOIN PESSOA PESS ON
      LOG.LOJA_ID = PESS.LOJA_ID
      AND LOG.TERMINAL_ID = PESS.TERMINAL_ID
      AND LOG.PESSOA_ID = PESS.PESSOA_ID
    INTO  
      :CAIXA_SESSAO_ID
      , :LOG_ID
      , :PESSOA_ID
      , :APELIDO
    DO  
      SUSPEND;
  END
END^
SET TERM ;^
