/*
in "C:\Pr\app\bantu\bantu-sis\Src\Externos\DBUpdates Complementos\Complementos\PDV\CAIXA_SESSAO_MANUT_PA.sql";


SELECT * FROM CAIXA_SESSAO_MANUT_PA.CAIXA_SESSAO_OPERACAO_INSERIR_DO(
1 -- LOJA_ID ID_SHORT_DOM NOT NULL
, 1 -- TERMINAL_ID ID_SHORT_DOM NOT NULL
, NULL -- SESS_ID ID_DOM
, NULL --SESS_LOG_ID BIGINT
, NULL -- OPER_ORDEM SMALLINT
, '!' -- OPER_TIPO_ID ID_CHAR_DOM Not Null
, NULL -- OPER_LOG_ID BIGINT
, NULL -- OPER_TIPO_ORDEM SMALLINT
, 2.35 -- VALOR PRECO_DOM Not Null
, 'PRIMEIRA ' -- OBS OBS_DOM
, -2 -- LOG_PESSOA_ID ID_DOM
, 1 -- MACHINE_ID ID_SHORT_DOM
);
ROLLBACK;
*/
SET TERM ^;
CREATE OR ALTER PACKAGE CAIXA_SESSAO_MANUT_PA
AS
BEGIN
  PROCEDURE ABERTO_GET
  RETURNS
  (
    SESS_ID ID_DOM
    , LOG_ID BIGINT
    , PESSOA_ID ID_DOM
    , APELIDO NOME_REDU_DOM
  );
  
  -- CAIXA_SESSAO_MANUT_PA.CAIXA_SESSAO_OPERACAO_INSERIR_DO DEF
  PROCEDURE CAIXA_SESSAO_OPERACAO_INSERIR_DO
  (
    LOJA_ID ID_SHORT_DOM NOT NULL
    , TERMINAL_ID ID_SHORT_DOM NOT NULL
    , SESS_ID ID_DOM
    , SESS_LOG_ID BIGINT
    , OPER_ORDEM SMALLINT
    , OPER_TIPO_ID ID_CHAR_DOM Not Null
    , OPER_LOG_ID BIGINT
    , OPER_TIPO_ORDEM SMALLINT
    , VALOR PRECO_DOM Not Null
    , OBS OBS_DOM
    , LOG_PESSOA_ID ID_DOM
    , MACHINE_ID ID_SHORT_DOM
  )
  RETURNS
  (
    SESS_ID_RET ID_DOM
    , SESS_LOG_ID_RET BIGINT
    , OPER_ORDEM_RET SMALLINT
    , OPER_LOG_ID_RET BIGINT
    , OPER_TIPO_ORDEM_RET SMALLINT
  );
END^

RECREATE PACKAGE BODY CAIXA_SESSAO_MANUT_PA
AS
BEGIN
  PROCEDURE ABERTO_GET
  RETURNS
  (
    SESS_ID ID_DOM
    , LOG_ID BIGINT
    , PESSOA_ID ID_DOM
    , APELIDO NOME_REDU_DOM
  )
  AS
  BEGIN
    FOR
      SELECT
      SESS.SESS_ID
      , SESS.LOG_ID
      , PESS.PESSOA_ID
      , PESS.APELIDO
      
      FROM AMBIENTE_SIS AMBI  

      JOIN CAIXA_SESSAO SESS ON
      AMBI.LOJA_ID = SESS.LOJA_ID
      AND AMBI.TERMINAL_ID = SESS.TERMINAL_ID

      JOIN LOG ON
      SESS.LOJA_ID = LOG.LOJA_ID
      AND SESS.TERMINAL_ID = LOG.TERMINAL_ID 
      AND SESS.LOG_ID = LOG.LOG_ID 

      JOIN PESSOA PESS ON
      LOG.LOJA_ID = PESS.LOJA_ID
      AND LOG.TERMINAL_ID = PESS.TERMINAL_ID
      AND LOG.PESSOA_ID = PESS.PESSOA_ID
    INTO  
      :SESS_ID
      , :LOG_ID
      , :PESSOA_ID
      , :APELIDO
    DO  
      SUSPEND;
  END
  
  -- CAIXA_SESSAO_MANUT_PA.CAIXA_SESSAO_OPERACAO_INSERIR_DO IMP
  PROCEDURE CAIXA_SESSAO_OPERACAO_INSERIR_DO
  (
    LOJA_ID ID_SHORT_DOM NOT NULL
    , TERMINAL_ID ID_SHORT_DOM NOT NULL
    , SESS_ID ID_DOM
    , SESS_LOG_ID BIGINT
    , OPER_ORDEM SMALLINT
    , OPER_TIPO_ID ID_CHAR_DOM Not Null
    , OPER_LOG_ID BIGINT
    , OPER_TIPO_ORDEM SMALLINT
    , VALOR PRECO_DOM Not Null
    , OBS OBS_DOM
    , LOG_PESSOA_ID ID_DOM
    , MACHINE_ID ID_SHORT_DOM
  )
  RETURNS
  (
    SESS_ID_RET ID_DOM
    , SESS_LOG_ID_RET BIGINT
    , OPER_ORDEM_RET SMALLINT
    , OPER_LOG_ID_RET BIGINT
    , OPER_TIPO_ORDEM_RET SMALLINT
  )
  AS
    -- LOJA INICIAL GAR LOGVAR LOGVARS VARS LOG VAR LOG VARLOG VARSLOG
    DECLARE SESS_FEATURE_SIS_ID ID_SHORT_DOM = 13; -- FEATURE SESSAO
    DECLARE OPER_FEATURE_SIS_ID ID_SHORT_DOM = 14; -- FEATURE OPERACAO
    
    DECLARE MODULO_SIS_ID ID_CHAR_DOM = '#'; -- MODULO PDV
    --DECLARE MODULO_SIS_ID ID_CHAR_DOM = '"'; -- RETAGUARDA
    DECLARE ACAO_SIS_ID ID_CHAR_DOM = '%'; -- INSERIR
    
    DECLARE PRECISA_INSERIR BOOLEAN;
  BEGIN
    -- CAIXA_SESSAO_MANUT_PA.CAIXA_SESSAO_OPERACAO_INSERIR_DO COD
    :SESS_ID_RET = COALESCE(SESS_ID, 0);
    
    :PRECISA_INSERIR = :SESS_ID_RET = 0;
    IF (:PRECISA_INSERIR) THEN
    BEGIN
      :SESS_ID_RET = NEXT VALUE FOR CAIXA_SESSAO_SEQ;

      SELECT LOG_ID_RET 
      FROM LOG_PA.LOG_NOVO_GET
      (
        :LOJA_ID,
        :TERMINAL_ID,
        :LOG_PESSOA_ID,
        :MODULO_SIS_ID,
        :ACAO_SIS_ID,
        :SESS_FEATURE_SIS_ID,
        :MACHINE_ID
      ) INTO :SESS_LOG_ID_RET;

      EXECUTE PROCEDURE LOG_PA.LOG_ENVOLVE_ID_INS
      (
        :LOJA_ID,
        :TERMINAL_ID,
        :SESS_LOG_ID_RET,
        0,

        NULL, -- LOJA_ID_ENVOLVIDO SMALLINT,
        NULL, -- TERMINAL_ID_ENVOLVIDO SMALLINT,
        SESS_ID_RET, -- ID_ENVOLVIDO INTEGER,
        0 -- ORDEM_ENVOLVIDO SMALLINT
      );
      
      INSERT INTO CAIXA_SESSAO
      (
        LOJA_ID
        , TERMINAL_ID
        , SESS_ID
        , LOG_ID
      )
      VALUES
      (
        :LOJA_ID
        , :TERMINAL_ID
        , :SESS_ID_RET
        , :SESS_LOG_ID_RET
      );
    END
    
    SUSPEND;    
  END
  /*
  :PRECISA_INSERIR = :OPER_ORDEM IS NULL;
  IF (:PRECISA_INSERIR) THEN
  BEGIN
    SELECT MAX(OPER_ORDEM) + 1 PROXIMO
    FROM CAIXA_SESSAO_OPERACAO
    WHERE LOJA_ID = :LOJA_ID
    AND TERMINAL_ID = :TERMINAL_ID
    AND SESS_ID = :SESS_ID_RET
    INTO :OPER_ORDEM;
    
    SELECT MAX(OPER_ORDEM) + 1 PROXIMO
    FROM CAIXA_SESSAO_OPERACAO
    WHERE LOJA_ID = :LOJA_ID
    AND TERMINAL_ID = :TERMINAL_ID
    AND SESS_ID = :SESS_ID_RET
    AND OPER_TIPO_ID = :OPER_TIPO_ID
    INTO :OPER_TIPO_ORDEM;
    
    
  */
END^
SET TERM ;^
