SET TERM ^;
CREATE OR ALTER PACKAGE CAIXA_SESSAO_INICIAL_PA
AS
BEGIN
  PROCEDURE CAIXA_SESSAO_GAR 
  (
    LOJA_ID ID_SHORT_DOM
    , TERMINAL_ID ID_SHORT_DOM
    , SESS_ID ID_DOM
    , SESS_LOG_ID BIGINT
    , ABERTO BOOLEAN
    , CONFERIDO BOOLEAN
  );

  PROCEDURE LISTA_GET
  (
    TEXTO_BUSCA VARCHAR(100)
  )
  RETURNS
  (
    NUM Integer
  );

  PROCEDURE LOG_ABE_FECH_GET
  (
    LOJA_ID ID_SHORT_DOM NOT NULL
    , TERMINAL_ID ID_SHORT_DOM NOT NULL
    , SESS_ID ID_DOM NOT NULL
  )
  RETURNS
  (
    ABE_LOG_ID BIGINT
    , FECH_LOG_ID BIGINT
  );

END^

RECREATE PACKAGE BODY CAIXA_SESSAO_INICIAL_PA
AS
BEGIN
  PROCEDURE CAIXA_SESSAO_GAR 
  (
    LOJA_ID ID_SHORT_DOM
    , TERMINAL_ID ID_SHORT_DOM
    , SESS_ID ID_DOM
    , SESS_LOG_ID BIGINT
    , ABERTO BOOLEAN
    , CONFERIDO BOOLEAN
  )
  AS
  BEGIN
    UPDATE OR INSERT INTO CAIXA_SESSAO
    (
      LOJA_ID,
      TERMINAL_ID,
      SESS_ID,
      SESS_LOG_ID,
      ABERTO,
      CONFERIDO
    )
    VALUES 
    (
      :LOJA_ID,
      :TERMINAL_ID,
      :SESS_ID,
      :SESS_LOG_ID,
      :ABERTO,
      :CONFERIDO
    )
    MATCHING (
      LOJA_ID,
      TERMINAL_ID,
      SESS_ID
    );
  END

  PROCEDURE LISTA_GET
  (
    TEXTO_BUSCA VARCHAR(100)
  )
  RETURNS
  (
    NUM Integer
  )
  AS 
  BEGIN 
  END

  PROCEDURE LOG_ABE_FECH_GET
  (
    LOJA_ID ID_SHORT_DOM NOT NULL
    , TERMINAL_ID ID_SHORT_DOM NOT NULL
    , SESS_ID ID_DOM NOT NULL
  )
  RETURNS
  (
    ABE_LOG_ID BIGINT
    , FECH_LOG_ID BIGINT
  )
  AS
  BEGIN
    SELECT 
      MAX(CASE WHEN OPER_TIPO_ID = '!' THEN OPER_LOG_ID END) AS ABE_LOG,
      COALESCE(MAX(CASE WHEN OPER_TIPO_ID = '(' THEN OPER_LOG_ID END), 0) AS FECH_LOG
    FROM CAIXA_SESSAO_OPERACAO
    WHERE LOJA_ID = :LOJA_ID 
      AND TERMINAL_ID = :TERMINAL_ID 
      AND SESS_ID = :SESS_ID
      AND OPER_TIPO_ID IN ('!', '(')
    INTO :ABE_LOG_ID, :FECH_LOG_ID;

    SUSPEND;
  END

END^
SET TERM ;^

/*
in "C:\Pr\app\bantu\bantu-sis\Src\Externos\DBUpdates Complementos\Complementos\PDV\CAIXA_SESSAO_INICIAL_PA.sql";
*/

/*
SELECT ABE_LOG_ID, FECH_LOG_ID FROM CAIXA_SESSAO_INICIAL_PA.LOG_ABE_FECH_GET(1, 3, 1);

*/