/*
in "C:\Pr\App\Bantu\bantu-sis\src\Externos\DBUpdates Complementos\Complementos\PDV\TESTE_pa.sql";


SELECT * FROM TESTE_PA.SESS_RELAT_BYID_GET(1, 1, 1);


*/
SET TERM ^;
CREATE OR ALTER PACKAGE TESTE_PA
AS
BEGIN

  PROCEDURE SESS_RELAT_BYID_GET
  (
    LOJA_ID ID_SHORT_DOM NOT NULL
    , TERMINAL_ID ID_SHORT_DOM NOT NULL
    , SESS_ID ID_DOM NOT NULL
  )
  RETURNS
  (
    LINHA VARCHAR(80)
  );
END^

---- BODY

RECREATE PACKAGE BODY TESTE_PA
AS
BEGIN

  PROCEDURE SESS_RELAT_BYID_GET
  (
    LOJA_ID ID_SHORT_DOM NOT NULL
    , TERMINAL_ID ID_SHORT_DOM NOT NULL
    , SESS_ID ID_DOM NOT NULL
  )
  RETURNS
  (
    LINHA VARCHAR(80)
  )
  AS
    -- INICIO DO RELATORIO INICIO
    DECLARE OPERADOR_LOJA_ID ID_SHORT_DOM;
    DECLARE OPERADOR_ID ID_DOM;
    DECLARE OPERADOR_APELIDO NOME_REDU_DOM;
    DECLARE CRIADO_EM TIMESTAMP;
    DECLARE FECHADO_EM TIMESTAMP;
    -- INICIO DO RELATORIO FIM

    DECLARE TIPO_ID ID_CHAR_DOM;
    DECLARE TIPO_NAME NOME_INTERM_DOM;
    DECLARE TIPO_SINAL_NUMERICO SMALLINT; 
    DECLARE TOTAL DINH_DOM;

    DECLARE COMPARE_FORMA_ID ID_SHORT_DOM;
    DECLARE COMPARE_DESCR NOME_DOM;
    DECLARE COMPARE_PAG_TOTAL DINH_DOM;
    DECLARE COMPARE_DIGITADO DINH_DOM;
    DECLARE COMPARE_DIF DINH_DOM;

    DECLARE POR_HORA_HORA SMALLINT;
    DECLARE POR_HORA_VOLUMES INTEGER;
    DECLARE POR_HORA_TICKETS INTEGER;
    DECLARE POR_HORA_TOTAL DINH_DOM;

  BEGIN
    -- INICIO DO RELATORIO INICIO
    SELECT
      OPERADOR_LOJA_ID
      , OPERADOR_ID
      , OPERADOR_APELIDO
      , CRIADO_EM
    FROM CAIXA_SESSAO_PDV_PA.SESS_GET
    (
      :LOJA_ID
      , :TERMINAL_ID
      , :SESS_ID
    )
    INTO
      :OPERADOR_LOJA_ID
      , :OPERADOR_ID
      , :OPERADOR_APELIDO
      , :CRIADO_EM;

    LINHA = :OPERADOR_LOJA_ID;
    SUSPEND;
    
    LINHA = :OPERADOR_ID;
    SUSPEND;
    
    LINHA = :OPERADOR_APELIDO;
    SUSPEND;
    
    LINHA = :CRIADO_EM;
    SUSPEND;
    -- INICIO DO RELATORIO FIM

    SELECT L.DTH 

    FROM CAIXA_SESSAO_OPERACAO O

    JOIN LOG L ON
    O.LOJA_ID = L.LOJA_ID
    AND O.TERMINAL_ID = L.TERMINAL_ID
    AND O.OPER_LOG_ID = L.LOG_ID

    WHERE O.LOJA_ID = :LOJA_ID
    AND O.TERMINAL_ID = :TERMINAL_ID 
    AND O.SESS_ID = :SESS_ID
    AND O.OPER_TIPO_ID = '('
    AND NOT O.CANCELADO
    INTO
      :FECHADO_EM;

    :FECHADO_EM = COALESCE(:FECHADO_EM, '1900-01-01 00:00:00.000');  

    LINHA = :FECHADO_EM;
    SUSPEND;
    
    FOR 
      SELECT 
        O.OPER_TIPO_ID
        , T.NAME
        , T.SINAL_NUMERICO
        , SUM(V.VALOR) AS TOTAL

      FROM CAIXA_SESSAO_OPERACAO_TIPO T

      JOIN CAIXA_SESSAO_OPERACAO O ON
      T.OPER_TIPO_ID = O.OPER_TIPO_ID

      JOIN CAIXA_SESSAO_OPERACAO_VALOR V ON
      O.LOJA_ID = V.LOJA_ID
      AND O.TERMINAL_ID = V.TERMINAL_ID
      AND O.SESS_ID = V.SESS_ID
      AND O.OPER_ORDEM = V.OPER_ORDEM

      WHERE NOT O.CANCELADO
      AND O.OPER_TIPO_ID <> '('

      GROUP BY 
        O.OPER_TIPO_ID
        , T.NAME
        , T.SINAL_NUMERICO
      ORDER BY
        O.OPER_TIPO_ID
    INTO
      :TIPO_ID
      , :TIPO_NAME
      , :TIPO_SINAL_NUMERICO
      , :TOTAL
     DO
     BEGIN
        LINHA = '2;' || :TIPO_NAME || ';' || :TIPO_SINAL_NUMERICO || ';' || :TOTAL;
        SUSPEND;
     END

    FOR
      SELECT 
        F.FORMA_ID
        , F.DESCR
        , COALESCE(D.TOTAL, 0) DIGITADO
        , P.TOTAL PAG_TOTAL
        , COALESCE(D.TOTAL, 0) - P.TOTAL DIF
      FROM CAIXA_SESSAO_PDV_PA.SESS_RELAT_PAGFORMA_LISTA_GET F

      LEFT JOIN CAIXA_SESSAO_PDV_PA.SESS_RELAT_FECH_TOTAIS_GET(1,1,1) D ON
      F.FORMA_ID = D.FORMA_ID

      JOIN CAIXA_SESSAO_PDV_PA.SESS_VENDA_PAG_TOTAL_GET(1,1,1) P ON
      F.FORMA_ID = P.FORMA_ID

      ORDER BY F.FORMA_ID
    INTO
      :COMPARE_FORMA_ID
      , :COMPARE_DESCR
      , :COMPARE_DIGITADO
      , :COMPARE_PAG_TOTAL
      , :COMPARE_DIF
    DO
    BEGIN
      LINHA = '3;' || :COMPARE_DESCR || ';' || :COMPARE_DIGITADO || ';' || :COMPARE_PAG_TOTAL || ';' || :COMPARE_DIF;
      SUSPEND;
    END

    FOR
      SELECT EXTRACT(HOUR FROM E.DTH_DOC) AS HORA
        , SUM(E.QTD_VOLUMES) QTD_VOLUMES
        , COUNT(E.EST_MOV_ID) QTD_TICKETS
        , SUM(V.TOTAL_LIQUIDO) TOTAL
      FROM VENDA V
      JOIN CAIXA_SESSAO_PDV_PA.SESS_RELAT_EST_MOV_LISTA_GET(1,1,1) E ON
      V.LOJA_ID = E.LOJA_ID
      AND V.TERMINAL_ID = E.TERMINAL_ID
      AND V.EST_MOV_ID = E.EST_MOV_ID
      AND V.LOJA_ID = :LOJA_ID
      AND V.TERMINAL_ID = :TERMINAL_ID
      AND V.SESS_ID = :SESS_ID
      GROUP BY EXTRACT(HOUR FROM E.DTH_DOC)
      ORDER BY EXTRACT(HOUR FROM E.DTH_DOC)
    INTO  
      :POR_HORA_HORA
      , :POR_HORA_VOLUMES
      , :POR_HORA_TICKETS
      , :POR_HORA_TOTAL
    DO
    BEGIN
      LINHA = '4;' || :POR_HORA_HORA 
        || ';' || :POR_HORA_VOLUMES
        || ';' || :POR_HORA_TICKETS
        || ';' || :POR_HORA_TOTAL;
      SUSPEND;
    END
  END
END^
SET TERM ;^
