      SELECT EXTRACT(HOUR FROM E.DTH_DOC) AS HORA
        , SUM(E.QTD_VOLUMES) QTD_VOLUMES
        , COUNT(E.EST_MOV_ID) QTD_TICKETS
        , SUM(V.TOTAL_LIQUIDO) TOTAL
      FROM VENDA V
      JOIN CAIXA_SESSAO_PDV_PA.SESS_RELAT_EST_MOV_LISTA_GET(1,1,1) E ON
      V.LOJA_ID = E.LOJA_ID
      AND V.TERMINAL_ID = E.TERMINAL_ID
      AND V.EST_MOV_ID = E.EST_MOV_ID
      AND V.LOJA_ID = :LOJA_ID
      AND V.TERMINAL_ID = :TERMINAL_ID
      AND V.SESS_ID = :SESS_ID
      GROUP BY EXTRACT(HOUR FROM E.DTH_DOC)
      ORDER BY EXTRACT(HOUR FROM E.DTH_DOC)

      
SELECT * FROM CAIXA_SESSAO_PDV_PA.EST_MOV_ITEM_VOLUMES_GET(1,1,3);

SELECT * FROM CAIXA_SESSAO_PDV_PA.SESS_RELAT_EST_MOV_LISTA_GET(1,1,1);





      SELECT E.LOJA_ID, E.TERMINAL_ID, E.EST_MOV_ID,
        SUM(CASE 
          WHEN I.QTD = CAST(I.QTD AS INTEGER) THEN I.QTD 
          ELSE 1 
        END) QTD_VOLUMES

      FROM EST_MOV E

      JOIN EST_MOV_ITEM I ON  
      E.LOJA_ID = I.LOJA_ID
      AND E.TERMINAL_ID = I.TERMINAL_ID
      AND E.EST_MOV_ID = I.EST_MOV_ID

      JOIN VENDA V ON
      V.LOJA_ID = E.LOJA_ID
      AND V.TERMINAL_ID = E.TERMINAL_ID
      AND V.EST_MOV_ID = E.EST_MOV_ID

      WHERE V.SESS_LOJA_ID = :SESS_LOJA_ID
      AND V.SESS_TERMINAL_ID = :SESS_TERMINAL_ID
      AND V.SESS_ID = :SESS_ID
      AND E.FINALIZADO
      AND NOT E.CANCELADO
      GROUP BY E.LOJA_ID, E.TERMINAL_ID, E.EST_MOV_ID

      
      
    FOR
      SELECT
      SESS.SESS_ID
      , PESS.PESSOA_ID
      , PESS.APELIDO
      , LOG.DTH ABERTO_EM
      
      FROM AMBIENTE_SIS AMBI  

      JOIN CAIXA_SESSAO SESS ON
      AMBI.LOJA_ID = SESS.LOJA_ID
      AND AMBI.TERMINAL_ID = SESS.TERMINAL_ID

      JOIN LOG ON
      SESS.LOJA_ID = LOG.LOJA_ID
      AND SESS.TERMINAL_ID = LOG.TERMINAL_ID 
      AND SESS.SESS_LOG_ID = LOG.LOG_ID 

      JOIN PESSOA PESS ON
      LOG.LOJA_ID = PESS.LOJA_ID
      AND LOG.PESSOA_TERMINAL_ID = PESS.TERMINAL_ID
      AND LOG.PESSOA_ID = PESS.PESSOA_ID

      WHERE SESS.ABERTO
      