

SET TERM ^;
CREATE OR ALTER PACKAGE PAGAMENTO_FORMA_PA
AS
BEGIN
  PROCEDURE LISTA_GET
  RETURNS
  (
    PAGAMENTO_FORMA_ID ID_SHORT_DOM
    , PAGAMENTO_FORMA_TIPO_ID ID_CHAR_DOM
    , DESCR NOME_INTERM_DOM
    , DESCR_RED CHAR(8)
    , ATIVO BOOLEAN
  );
END^

RECREATE PACKAGE BODY PAGAMENTO_FORMA_PA
AS
BEGIN
  PROCEDURE LISTA_GET
  RETURNS
  (
    FORMA_ID ID_SHORT_DOM
    , FORMA_TIPO_DESCR NOME_INTERM_DOM
    , DESCR NOME_INTERM_DOM
    , DESCR_RED CHAR(8)
    , PARA_VENDA BOOLEAN
    , ATIVO BOOLEAN
  )
  AS
  BEGIN
    FOR SELECT F.ID, FORMA_TIPO_DESCR,
      PF.DESCR, PF.DESCR_RED, PF.ATIVO
    FROM PAGAMENTO_FORMA PF 
    ORDER BY PF.PAGAMENTO_FORMA_TIPO_ID, PF.PAGAMENTO_FORMA_ID
    INTO :PAGAMENTO_FORMA_ID, :PAGAMENTO_FORMA_TIPO_ID,
      :DESCR, :DESCR_RED, :ATIVO
    DO SUSPEND; 
  END
END^
SET TERM ;^

show package PAGAMENTO_FORMA_PA;
