

SET TERM ^;
CREATE OR ALTER PACKAGE PAGAMENTO_FORMA_PA
AS
BEGIN
  PROCEDURE LISTA_GET
  RETURNS
  (
    FORMA_ID ID_SHORT_DOM
    , FORMA_TIPO_DESCR NOME_INTERM_DOM
    , DESCR NOME_INTERM_DOM
    , DESCR_RED CHAR(8)
    , PARA_VENDA BOOLEAN
    , ATIVO BOOLEAN
  );
END^

RECREATE PACKAGE BODY PAGAMENTO_FORMA_PA
AS
BEGIN
  PROCEDURE LISTA_GET
  RETURNS
  (
    FORMA_ID ID_SHORT_DOM
    , FORMA_TIPO_DESCR NOME_INTERM_DOM
    , DESCR NOME_INTERM_DOM
    , DESCR_RED CHAR(8)
    , PARA_VENDA BOOLEAN
    , ATIVO BOOLEAN
  )
  AS
  BEGIN
    FOR
    WITH F AS (
      SELECT PAGAMENTO_FORMA_ID ID, PAGAMENTO_FORMA_TIPO_ID TIPO_ID,
        DESCR, DESCR_RED, PARA_VENDA, ATIVO
      FROM PAGAMENTO_FORMA  
    ),
    FT AS (
      SELECT PAGAMENTO_FORMA_TIPO_ID TIPO_ID, DESCR
      FROM PAGAMENTO_FORMA_TIPO
    )
    SELECT F.ID, FT.DESCR,
      F.DESCR, F.DESCR_RED, F.PARA_VENDA, F.ATIVO
    FROM F
    JOIN FT ON F.TIPO_ID = FT.TIPO_ID
    ORDER BY F.TIPO_ID, F.ID
    INTO :FORMA_ID, :FORMA_TIPO_DESCR, :DESCR, :DESCR_RED,
      :PARA_VENDA, :ATIVO
    DO SUSPEND; 
  END
END^
SET TERM ;^

--show package PAGAMENTO_FORMA_PA;
