SET TERM ^;
CREATE OR ALTER PACKAGE PAGAMENTO_FORMA_PA
AS
BEGIN
  PROCEDURE LISTA_GET
  RETURNS
  (
    FORMA_ID ID_SHORT_DOM
    , FORMA_TIPO_DESCR NOME_INTERM_DOM
    , DESCR NOME_INTERM_DOM
    , DESCR_RED CHAR(8)
    , PARA_VENDA BOOLEAN
    , ATIVO BOOLEAN
  );

  PROCEDURE ABREV_LISTA_GET
  RETURNS
  (
    FORMA_ID ID_SHORT_DOM
    , DESCR NOME_DOM
  );
END^

------ BODY ------

RECREATE PACKAGE BODY PAGAMENTO_FORMA_PA
AS
BEGIN
  PROCEDURE LISTA_GET
  RETURNS
  (
    FORMA_ID ID_SHORT_DOM
    , FORMA_TIPO_DESCR NOME_INTERM_DOM
    , DESCR NOME_INTERM_DOM
    , DESCR_RED CHAR(8)
    , PARA_VENDA BOOLEAN
    , ATIVO BOOLEAN
  )
  AS
  BEGIN
    FOR
    WITH F AS (
      SELECT PAGAMENTO_FORMA_ID ID, PAGAMENTO_FORMA_TIPO_ID TIPO_ID,
        DESCR, DESCR_RED, PARA_VENDA, ATIVO
      FROM PAGAMENTO_FORMA  
    ),
    FT AS (
      SELECT PAGAMENTO_FORMA_TIPO_ID TIPO_ID, DESCR
      FROM PAGAMENTO_FORMA_TIPO
    )
    SELECT F.ID, FT.DESCR,
      F.DESCR, F.DESCR_RED, F.PARA_VENDA, F.ATIVO
    FROM F
    JOIN FT ON F.TIPO_ID = FT.TIPO_ID
    ORDER BY F.TIPO_ID, F.ID
    INTO :FORMA_ID, :FORMA_TIPO_DESCR, :DESCR, :DESCR_RED,
      :PARA_VENDA, :ATIVO
    DO SUSPEND; 
  END
  
  PROCEDURE ABREV_LISTA_GET
  RETURNS
  (
    FORMA_ID ID_SHORT_DOM
    , DESCR NOME_DOM
  )
  AS
  BEGIN
    FOR
      WITH TIPO AS 
      (
        SELECT PAGAMENTO_FORMA_TIPO_ID ID, DESCR_RED
        FROM PAGAMENTO_FORMA_TIPO
      ), FORMA AS
      (
          SELECT PAGAMENTO_FORMA_ID ID, PAGAMENTO_FORMA_TIPO_ID TIPO_ID, DESCR_RED
          FROM PAGAMENTO_FORMA
          WHERE PARA_VENDA
      )
      SELECT 
        FORMA.ID, 
        CASE
          WHEN TIPO.ID = '!' THEN TRIM(FORMA.DESCR_RED)
          WHEN TIPO.ID = '"' THEN TRIM(FORMA.DESCR_RED) || ' ' || TRIM(TIPO.DESCR_RED)
          WHEN TIPO.ID = '#' THEN TRIM(FORMA.DESCR_RED) || ' ' || TRIM(TIPO.DESCR_RED)
          WHEN TIPO.ID = '$' THEN TRIM(FORMA.DESCR_RED)
        END AS DESCR
      FROM TIPO
      JOIN FORMA ON
      TIPO.ID = FORMA.TIPO_ID
      ORDER BY FORMA.ID
    INTO :FORMA_ID, :DESCR
    DO SUSPEND;
  END
END^
SET TERM ;^
