SET TERM ^;
CREATE OR ALTER PACKAGE USUARIO_PA
AS
BEGIN
  PROCEDURE GARANTIR_NOMES
  (
    LOJA_ID ID_SHORT_DOM NOT NULL,
    NOME NOME_DOM NOT NULL,
    NOME_DE_USUARIO NOME_REDU_DOM NOT NULL,
    SENHA SENHA_DOM NOT NULL,
    CRY_VER ID_SHORT_DOM NOT NULL,
    APELIDO NOME_REDU_DOM NOT NULL,
    PESSOA_ID INTEGER
  )
  RETURNS
  (
    PESSOA_ID_RETORNADA INTEGER 
  );

  PROCEDURE GARANTIR
  (
    LOJA_ID SMALLINT NOT NULL,
    NOME VARCHAR(60),
    NOME_DE_USUARIO VARCHAR(20) NOT NULL,
    SENHA VARCHAR(80) NOT NULL,
    CRY_VER SMALLINT NOT NULL,
    APELIDO VARCHAR(20),
    NOME_FANTASIA VARCHAR(60),
    GENERO_ID CHAR(1),
    ESTADO_CIVIL_ID CHAR(1),
    C VARCHAR(15),
    I VARCHAR(15),
    M VARCHAR(15),
    M_UF CHAR(2),
    EMAIL VARCHAR(50),
    DT_NASC DATE,
    PESSOA_ID INTEGER
  )
  RETURNS
  (
    PESSOA_ID_RETORNADA INTEGER
  );

  PROCEDURE USUARIO_TEM_PERFIL_USO_GARANTIR(
    LOJA_ID ID_SHORT_NOTN_DOM,
    USUARIO_ID INTEGER NOT NULL,
    PERFIL_USO_ID ID_SHORT_NOTN_DOM
  );

  PROCEDURE USUARIO_ACESSA_MODULO_GARANTIR(
    LOJA_ID ID_SHORT_NOTN_DOM,
    USUARIO_ID INTEGER NOT NULL,
    MODULO_ID ID_CHAR_DOM NOT NULL
  );

  PROCEDURE USUARIO_TRAZER_MODULOS (
    LOJA_ID SMALLINT NOT NULL,
    USUARIO_ID INTEGER NOT NULL,
    PERFIL_USO_ID SMALLINT NOT NULL
  );

  PROCEDURE BY_NOME_DE_USUARIO (NOME_DE_USUARIO VARCHAR(20) NOT NULL)
  RETURNS (LOJA_ID SMALLINT, USUARIO_ID INTEGER, NOME VARCHAR(60), APELIDO VARCHAR(20), CRY_VER SMALLINT, SENHA VARCHAR(80));

  PROCEDURE USUARIO_ACESSA_MODULO_GET (
    LOJA_ID SMALLINT NOT NULL,
    USUARIO_ID INTEGER NOT NULL,
    MODULO_ID ID_CHAR_DOM NOT NULL
  ) RETURNS (
    ACESSA BOOLEAN
  );

END^

RECREATE PACKAGE BODY USUARIO_PA
AS
BEGIN
  PROCEDURE GARANTIR_NOMES
  (
    LOJA_ID ID_SHORT_DOM NOT NULL,
    NOME NOME_DOM NOT NULL,
    NOME_DE_USUARIO NOME_REDU_DOM NOT NULL,
    SENHA SENHA_DOM NOT NULL,
    CRY_VER ID_SHORT_DOM NOT NULL,
    APELIDO NOME_REDU_DOM NOT NULL,
    PESSOA_ID INTEGER
  )
  RETURNS
  (
    PESSOA_ID_RETORNADA INTEGER 
  )
  AS
  BEGIN
    EXECUTE PROCEDURE FUNCIONARIO_PA.GARANTIR_NOMES(:LOJA_ID, :NOME, :APELIDO, :PESSOA_ID)
      RETURNING_VALUES :PESSOA_ID_RETORNADA;
    
    UPDATE OR INSERT INTO USUARIO (LOJA_ID, TERMINAL_ID, USUARIO_ID, NOME_DE_USUARIO, SENHA, CRY_VER)
    VALUES (:LOJA_ID, 0, :PESSOA_ID_RETORNADA, :NOME_DE_USUARIO, :SENHA, :CRY_VER)
    MATCHING (LOJA_ID, TERMINAL_ID, USUARIO_ID);
    
    SUSPEND; -- RETORNA O VALOR DE PESSOA_ID_RETORNADA
  END

  PROCEDURE GARANTIR
  (
    LOJA_ID SMALLINT NOT NULL,
    NOME VARCHAR(60),
    NOME_DE_USUARIO VARCHAR(20) NOT NULL,
    SENHA VARCHAR(80) NOT NULL,
    CRY_VER SMALLINT NOT NULL,
    APELIDO VARCHAR(20),
    NOME_FANTASIA VARCHAR(60),
    GENERO_ID CHAR(1),
    ESTADO_CIVIL_ID CHAR(1),
    C VARCHAR(15),
    I VARCHAR(15),
    M VARCHAR(15),
    M_UF CHAR(2),
    EMAIL VARCHAR(50),
    DT_NASC DATE,
    PESSOA_ID INTEGER
  )
  RETURNS
  (
    PESSOA_ID_RETORNADA INTEGER
  )
  AS
  BEGIN
    EXECUTE PROCEDURE FUNCIONARIO_PA.GARANTIR(:LOJA_ID, 0, :NOME, :NOME_FANTASIA, :APELIDO, :GENERO_ID, :ESTADO_CIVIL_ID, :C, :I, :M, :M_UF, :EMAIL, :DT_NASC, :PESSOA_ID)
      RETURNING_VALUES :PESSOA_ID_RETORNADA;

    UPDATE OR INSERT INTO USUARIO (LOJA_ID, TERMINAL_ID, USUARIO_ID, NOME_DE_USUARIO, SENHA, CRY_VER)
    VALUES (:LOJA_ID, 0, :PESSOA_ID_RETORNADA, :NOME_DE_USUARIO, :SENHA, :CRY_VER)
    MATCHING (LOJA_ID, TERMINAL_ID, USUARIO_ID);

    SUSPEND; -- RETORNA O VALOR DE PESSOA_ID_RETORNADA
  END


  PROCEDURE USUARIO_TEM_PERFIL_USO_GARANTIR(
    LOJA_ID ID_SHORT_NOTN_DOM,
    USUARIO_ID INTEGER NOT NULL,
    PERFIL_USO_ID ID_SHORT_NOTN_DOM
  )
  AS
  BEGIN
    UPDATE OR INSERT INTO USUARIO_TEM_PERFIL_USO (LOJA_ID, TERMINAL_ID, USUARIO_ID, PERFIL_USO_ID)
    VALUES (:LOJA_ID, 0, :USUARIO_ID, :PERFIL_USO_ID)
    MATCHING (LOJA_ID, TERMINAL_ID, USUARIO_ID, PERFIL_USO_ID);

    EXECUTE PROCEDURE USUARIO_TRAZER_MODULOS (LOJA_ID, USUARIO_ID, PERFIL_USO_ID);
  END

  PROCEDURE USUARIO_ACESSA_MODULO_GARANTIR(
    LOJA_ID ID_SHORT_NOTN_DOM,
    USUARIO_ID INTEGER NOT NULL,
    MODULO_ID ID_CHAR_DOM NOT NULL
  )
  AS
  BEGIN
    UPDATE OR INSERT INTO USUARIO_ACESSA_MODULO (LOJA_ID, TERMINAL_ID, USUARIO_ID, MODULO_ID)
    VALUES (:LOJA_ID, 0, :USUARIO_ID, :MODULO_ID)
    MATCHING (LOJA_ID, TERMINAL_ID, USUARIO_ID, MODULO_ID);
  END

  PROCEDURE USUARIO_TRAZER_MODULOS (
    LOJA_ID SMALLINT NOT NULL,
    USUARIO_ID INTEGER NOT NULL,
    PERFIL_USO_ID SMALLINT NOT NULL
  )
  AS
    DECLARE VARIABLE MODULO_ID ID_CHAR_DOM;
  BEGIN
    DELETE FROM USUARIO_ACESSA_MODULO
    WHERE LOJA_ID = :LOJA_ID
    AND TERMINAL_ID = 0
    AND USUARIO_ID = :USUARIO_ID;

    FOR SELECT MODULO_ID
    FROM PERFIL_USO_ACESSA_MODULO
    WHERE PERFIL_USO_ID = :PERFIL_USO_ID
    INTO :MODULO_ID
    DO
    BEGIN
      INSERT INTO USUARIO_ACESSA_MODULO (LOJA_ID, TERMINAL_ID, USUARIO_ID, MODULO_ID)
      VALUES (:LOJA_ID, 0, :USUARIO_ID, :MODULO_ID);
    END
  END

  PROCEDURE BY_NOME_DE_USUARIO (NOME_DE_USUARIO VARCHAR(20) NOT NULL)
  RETURNS (LOJA_ID SMALLINT, USUARIO_ID INTEGER, NOME VARCHAR(60), APELIDO VARCHAR(20), CRY_VER SMALLINT, SENHA VARCHAR(80))
  AS
  BEGIN
    FOR SELECT p.LOJA_ID, p.PESSOA_ID, P.NOME, p.APELIDO, u.CRY_VER, u.SENHA
    FROM pessoa p
    JOIN usuario u ON 
    p.LOJA_ID = u.LOJA_ID 
    AND p.TERMINAL_ID = 0
    AND p.TERMINAL_ID = u.TERMINAL_ID 
    AND p.PESSOA_ID = u.USUARIO_ID
    WHERE u.NOME_DE_USUARIO = :NOME_DE_USUARIO
    INTO :LOJA_ID, :USUARIO_ID, :NOME, :APELIDO, :CRY_VER, :SENHA
    DO
    BEGIN
      SUSPEND;
    END
  END

  PROCEDURE USUARIO_ACESSA_MODULO_GET (
    LOJA_ID SMALLINT NOT NULL,
    USUARIO_ID INTEGER NOT NULL,
    MODULO_ID ID_CHAR_DOM NOT NULL
  ) RETURNS (
    ACESSA BOOLEAN
  )
  AS
  DECLARE VARIABLE RESULTADO INTEGER;
  BEGIN
    SELECT 1 FROM RDB$DATABASE WHERE EXISTS (
    SELECT USUARIO_ID
    FROM USUARIO_ACESSA_MODULO
    WHERE LOJA_ID = :LOJA_ID
    AND TERMINAL_ID = 0
    AND USUARIO_ID = :USUARIO_ID
    AND MODULO_ID = :MODULO_ID
    ) INTO :RESULTADO;

    :ACESSA = :RESULTADO = 1;
    SUSPEND;
  END
END^
SET TERM ;^
```
